// 110+ Rebus - söz düzmek oýny
export const REBUSES = [
  // Harplary dogry düz
  { id:1, level:'beginner', type:'unscramble', scrambled:'TAC', answer:'CAT', hint:'🐱 Öý haýwany', tk:'pişik', ru:'кошка' },
  { id:2, level:'beginner', type:'unscramble', scrambled:'GOD', answer:'DOG', hint:'🐕 Wepaly haýwan', tk:'it', ru:'собака' },
  { id:3, level:'beginner', type:'unscramble', scrambled:'DRE', answer:'RED', hint:'🔴 Reňk', tk:'gyzyl', ru:'красный' },
  { id:4, level:'beginner', type:'unscramble', scrambled:'NUS', answer:'SUN', hint:'☀️ Asmanda bar', tk:'gün', ru:'солнце' },
  { id:5, level:'beginner', type:'unscramble', scrambled:'KSY', answer:'SKY', hint:'🌤️ Asmanyň ady', tk:'asman', ru:'небо' },
  { id:6, level:'beginner', type:'unscramble', scrambled:'AGR', answer:'GAR', hint:'⬛ Gara reňk däl... (Tk: ...)', tk:'gar', ru:'снег' },
  { id:7, level:'beginner', type:'unscramble', scrambled:'EYE', answer:'EYE', hint:'👁️ Görüş organy', tk:'göz', ru:'глаз' },
  { id:8, level:'beginner', type:'unscramble', scrambled:'RAE', answer:'EAR', hint:'👂 Eşidiş organy', tk:'gulak', ru:'ухо' },
  { id:9, level:'beginner', type:'unscramble', scrambled:'GLE', answer:'LEG', hint:'🦵 Ýöremek üçin', tk:'aýak', ru:'нога' },
  { id:10, level:'beginner', type:'unscramble', scrambled:'MRA', answer:'ARM', hint:'💪 Bilekden barmaklara çenli', tk:'gol', ru:'рука' },
  { id:11, level:'beginner', type:'unscramble', scrambled:'GEB', answer:'BEG', hint:'🙏 Haýyş etmek', tk:'haýyş', ru:'просить' },
  { id:12, level:'beginner', type:'unscramble', scrambled:'TCA', answer:'ACT', hint:'🎭 Oýna goşulmak', tk:'oýnamak', ru:'играть' },
  { id:13, level:'beginner', type:'unscramble', scrambled:'LFOW', answer:'WOLF', hint:'🐺 Tokaý haýwany', tk:'möjek', ru:'волк' },
  { id:14, level:'beginner', type:'unscramble', scrambled:'SIFH', answer:'FISH', hint:'🐟 Suwda ýaşaýar', tk:'balyk', ru:'рыба' },
  { id:15, level:'beginner', type:'unscramble', scrambled:'RIDB', answer:'BIRD', hint:'🐦 Uçýar', tk:'guş', ru:'птица' },
  { id:16, level:'beginner', type:'unscramble', scrambled:'KAER', answer:'RAKE', hint:'🍂 Bagy süpürmek üçin', tk:'dyrnak', ru:'грабли' },
  { id:17, level:'beginner', type:'unscramble', scrambled:'EKLA', answer:'LAKE', hint:'💧 Uly suw', tk:'köl', ru:'озеро' },
  { id:18, level:'beginner', type:'unscramble', scrambled:'ACFE', answer:'FACE', hint:'😊 Siziň..', tk:'ýüz', ru:'лицо' },
  { id:19, level:'beginner', type:'unscramble', scrambled:'KOCO', answer:'COOK', hint:'👨‍🍳 Nahar bişirýär', tk:'aşpez', ru:'повар' },
  { id:20, level:'beginner', type:'unscramble', scrambled:'KOBO', answer:'BOOK', hint:'📚 Okamak üçin', tk:'kitap', ru:'книга' },

  // Fill in the blank - Boş ýeri doldur
  { id:21, level:'beginner', type:'fill', question:'A ___ lives in the sea', options:['fish','bird','wolf','horse'], answer:'fish', hint:'🐟' },
  { id:22, level:'beginner', type:'fill', question:'The ___ shines in the sky', options:['moon','star','sun','cloud'], answer:'sun', hint:'☀️' },
  { id:23, level:'beginner', type:'fill', question:'I drink ___ every morning', options:['bread','water','chair','table'], answer:'water', hint:'💧' },
  { id:24, level:'beginner', type:'fill', question:'A ___ has four legs', options:['fish','bird','horse','snake'], answer:'horse', hint:'🐴' },
  { id:25, level:'beginner', type:'fill', question:'We read a ___', options:['car','book','door','window'], answer:'book', hint:'📖' },
  { id:26, level:'beginner', type:'fill', question:'I sleep in my ___', options:['kitchen','bathroom','bed','chair'], answer:'bed', hint:'🛏️' },
  { id:27, level:'beginner', type:'fill', question:'The sky is ___', options:['red','blue','green','black'], answer:'blue', hint:'🌤️' },
  { id:28, level:'beginner', type:'fill', question:'A ___ is a big animal with a long nose', options:['lion','tiger','elephant','bear'], answer:'elephant', hint:'🐘' },
  { id:29, level:'beginner', type:'fill', question:'I write with a ___', options:['book','table','pen','chair'], answer:'pen', hint:'✏️' },
  { id:30, level:'beginner', type:'fill', question:'The grass is ___', options:['red','yellow','green','blue'], answer:'green', hint:'🌿' },

  // Word association - Söz baglanyşygy
  { id:31, level:'intermediate', type:'fill', question:'A doctor works in a ___', options:['school','hospital','market','park'], answer:'hospital', hint:'🏥' },
  { id:32, level:'intermediate', type:'fill', question:'A teacher works in a ___', options:['hospital','factory','school','farm'], answer:'school', hint:'🏫' },
  { id:33, level:'intermediate', type:'fill', question:'You ___ food, you don\'t eat clothes', options:['wear','drink','eat','sleep'], answer:'eat', hint:'🍽️' },
  { id:34, level:'intermediate', type:'fill', question:'You ___ clothes, you don\'t wear food', options:['eat','drink','wear','sleep'], answer:'wear', hint:'👔' },
  { id:35, level:'intermediate', type:'fill', question:'Planes ___ in the sky', options:['swim','walk','fly','run'], answer:'fly', hint:'✈️' },
  { id:36, level:'intermediate', type:'fill', question:'Fish ___ in water', options:['fly','walk','swim','run'], answer:'swim', hint:'🐟' },
  { id:37, level:'intermediate', type:'fill', question:'Summer is ___, winter is cold', options:['wet','dry','hot','dark'], answer:'hot', hint:'🌡️' },
  { id:38, level:'intermediate', type:'fill', question:'Night is ___, day is bright', options:['hot','dark','loud','fast'], answer:'dark', hint:'🌙' },
  { id:39, level:'intermediate', type:'fill', question:'Honey is ___, lemon is sour', options:['bitter','salty','sweet','spicy'], answer:'sweet', hint:'🍯' },
  { id:40, level:'intermediate', type:'fill', question:'Ice is ___', options:['hot','warm','cold','dry'], answer:'cold', hint:'🧊' },

  // Scrambled words - intermediate
  { id:41, level:'intermediate', type:'unscramble', scrambled:'ANOBNA', answer:'BANANA', hint:'🍌 Sary miwesi bar', tk:'banan', ru:'банан' },
  { id:42, level:'intermediate', type:'unscramble', scrambled:'LEAPNAH', answer:'ELEPHANT', hint:'🐘 Iň uly ýer haýwany', tk:'pil', ru:'слон' },
  { id:43, level:'intermediate', type:'unscramble', scrambled:'RAEINGT', answer:'GRANITE', hint:'🪨 Daş görnüşi', tk:'granit', ru:'гранит' },
  { id:44, level:'intermediate', type:'unscramble', scrambled:'TACMOT', answer:'TOMCAT', hint:'🐱 Erkek pişik', tk:'erkek pişik', ru:'кот' },
  { id:45, level:'intermediate', type:'unscramble', scrambled:'CIKHTCE', answer:'KITCHEN', hint:'🍳 Nahar bişirilýän ýer', tk:'aşhana', ru:'кухня' },
  { id:46, level:'intermediate', type:'unscramble', scrambled:'NWODWI', answer:'WINDOW', hint:'🪟 Öýdäki cam', tk:'penjire', ru:'окно' },
  { id:47, level:'intermediate', type:'unscramble', scrambled:'DRAEG', answer:'GRADE', hint:'📊 Okuwda baha', tk:'baha', ru:'оценка' },
  { id:48, level:'intermediate', type:'unscramble', scrambled:'IRGBE', answer:'BRIDE', hint:'👰 Toý günündäki gyz', tk:'gelinlik', ru:'невеста' },
  { id:49, level:'intermediate', type:'unscramble', scrambled:'GLEENA', answer:'ELEGANT', hint:'✨ Owadan we täsin', tk:'gelşikli', ru:'элегантный' },
  { id:50, level:'intermediate', type:'unscramble', scrambled:'TACHREC', answer:'CHARTER', hint:'📜 Resmi resminama', tk:'harta', ru:'хартия' },
  { id:51, level:'intermediate', type:'unscramble', scrambled:'PEAMT', answer:'TEMPT', hint:'😈 Imana getirmek', tk:'aldatmak', ru:'соблазнять' },
  { id:52, level:'intermediate', type:'unscramble', scrambled:'PICSART', answer:'ASTIC', hint:'Sözüň dowamy...', tk:'...', ru:'...' },
  { id:53, level:'intermediate', type:'unscramble', scrambled:'NOMKEY', answer:'MONKEY', hint:'🐒 Agaçda oýnaýar', tk:'maýmyn', ru:'обезьяна' },
  { id:54, level:'intermediate', type:'unscramble', scrambled:'ORWELF', answer:'FLOWER', hint:'🌸 Owadan guller', tk:'gül', ru:'цветок' },
  { id:55, level:'intermediate', type:'unscramble', scrambled:'DEBARR', answer:'BARRED', hint:'🚫 Gadagan', tk:'gadagan', ru:'запрещённый' },
  { id:56, level:'intermediate', type:'unscramble', scrambled:'RECAHO', answer:'OCHRE', hint:'🎨 Sarymtyl reňk', tk:'sarymtyl', ru:'охра' },
  { id:57, level:'intermediate', type:'unscramble', scrambled:'DANREG', answer:'GARDEN', hint:'🌿 Öý bagy', tk:'bagy', ru:'сад' },
  { id:58, level:'intermediate', type:'unscramble', scrambled:'DRACGE', answer:'GRACED', hint:'🌟 Bezenen', tk:'bezelen', ru:'украшенный' },
  { id:59, level:'intermediate', type:'unscramble', scrambled:'LAMACIN', answer:'MANICAL', hint:'😵 Dälice', tk:'dälice', ru:'маниакальный' },
  { id:60, level:'intermediate', type:'unscramble', scrambled:'NICEKAR', answer:'CRINKLE', hint:'👴 Ýüzdäki garaşyk', tk:'garaşyk', ru:'морщина' },

  // Fill blank - advanced
  { id:61, level:'advanced', type:'fill', question:'The ___ of the company is to make profit', options:['dream','goal','play','game'], answer:'goal', hint:'🎯' },
  { id:62, level:'advanced', type:'fill', question:'Without ___, there can be no progress', options:['money','effort','luck','talent'], answer:'effort', hint:'💪' },
  { id:63, level:'advanced', type:'fill', question:'Education is the key to ___', options:['money','happiness','success','fame'], answer:'success', hint:'🎓' },
  { id:64, level:'advanced', type:'fill', question:'A leader must have good ___ skills', options:['eating','sleeping','communication','cooking'], answer:'communication', hint:'💬' },
  { id:65, level:'advanced', type:'fill', question:'Democracy requires citizen ___', options:['silence','participation','obedience','wealth'], answer:'participation', hint:'🗳️' },
  { id:66, level:'advanced', type:'fill', question:'Science ___ new discoveries every year', options:['destroys','makes','breaks','stops'], answer:'makes', hint:'🔬' },
  { id:67, level:'advanced', type:'fill', question:'___ is the mother of invention', options:['Money','Luck','Necessity','Time'], answer:'Necessity', hint:'💡' },
  { id:68, level:'advanced', type:'fill', question:'Knowledge ___ power', options:['loses','gives','destroys','takes'], answer:'gives', hint:'📚' },
  { id:69, level:'advanced', type:'fill', question:'Time is ___', options:['free','cheap','money','infinite'], answer:'money', hint:'⏰' },
  { id:70, level:'advanced', type:'fill', question:'Practice makes ___', options:['money','perfect','friends','enemies'], answer:'perfect', hint:'🏆' },

  // Advanced unscramble
  { id:71, level:'advanced', type:'unscramble', scrambled:'YCNOMED', answer:'ECONOMY', hint:'📊 Milli hojalyk', tk:'ykdysadyýet', ru:'экономика' },
  { id:72, level:'advanced', type:'unscramble', scrambled:'ICTEADNUO', answer:'EDUCATION', hint:'🎓 Bilim almak', tk:'bilim', ru:'образование' },
  { id:73, level:'advanced', type:'unscramble', scrambled:'YTRECOMD', answer:'DEMOCRACY', hint:'🗳️ Dolandyryş görnüşi', tk:'demokratiýa', ru:'демократия' },
  { id:74, level:'advanced', type:'unscramble', scrambled:'CYIOSET', answer:'SOCIETY', hint:'👥 Jemgyýet', tk:'jemgyýet', ru:'общество' },
  { id:75, level:'advanced', type:'unscramble', scrambled:'IOPSHPOHL', answer:'PHILOSOPHY', hint:'🤔 Akyldarlyk', tk:'filosofiýa', ru:'философия' },
  { id:76, level:'advanced', type:'unscramble', scrambled:'YOLCTEHNOG', answer:'TECHNOLOGY', hint:'💻 Häzirki zaman bilimi', tk:'tehnologiýa', ru:'технология' },
  { id:77, level:'advanced', type:'unscramble', scrambled:'NMREONTIVNE', answer:'ENVIRONMENT', hint:'🌍 Daşky gurşaw', tk:'daşky gurşaw', ru:'окружающая среда' },
  { id:78, level:'advanced', type:'unscramble', scrambled:'IODCTIRNIT', answer:'TRADITION', hint:'🏛️ Däp-dessurlary', tk:'däp-dessur', ru:'традиция' },
  { id:79, level:'advanced', type:'unscramble', scrambled:'OLUVIRTNOE', answer:'REVOLUTION', hint:'✊ Uly özgerişlik', tk:'rewolýusiýa', ru:'революция' },
  { id:80, level:'advanced', type:'unscramble', scrambled:'NDEICNEPEDEN', answer:'INDEPENDENCE', hint:'🗽 Özbaşdaklyk', tk:'garaşsyzlyk', ru:'независимость' },

  // Picture clues - Additional rebuses
  { id:81, level:'beginner', type:'fill', question:'🌧️ When it rains, the sky has ___', options:['clouds','stars','sun','rainbow'], answer:'clouds', hint:'☁️' },
  { id:82, level:'beginner', type:'fill', question:'🎄 Christmas tree is ___', options:['red','blue','green','yellow'], answer:'green', hint:'🌲' },
  { id:83, level:'beginner', type:'fill', question:'🐝 A bee makes ___', options:['milk','honey','butter','jam'], answer:'honey', hint:'🍯' },
  { id:84, level:'beginner', type:'fill', question:'🌙 At night we see the ___', options:['sun','star','moon','cloud'], answer:'moon', hint:'🌕' },
  { id:85, level:'beginner', type:'fill', question:'❄️ In winter it ___', options:['rains','snows','shines','floods'], answer:'snows', hint:'⛄' },
  { id:86, level:'intermediate', type:'fill', question:'🏊 Olympic ___ is held every 4 years', options:['festival','games','concert','exam'], answer:'games', hint:'🏅' },
  { id:87, level:'intermediate', type:'fill', question:'📞 Before texting, people used to ___', options:['email','call','tweet','post'], answer:'call', hint:'📱' },
  { id:88, level:'intermediate', type:'fill', question:'🌍 The biggest ___ is Russia', options:['city','ocean','country','river'], answer:'country', hint:'🗺️' },
  { id:89, level:'intermediate', type:'fill', question:'🔬 Scientists work in a ___', options:['farm','laboratory','hospital','school'], answer:'laboratory', hint:'⚗️' },
  { id:90, level:'intermediate', type:'fill', question:'🎭 Shakespeare was a famous ___', options:['painter','writer','singer','dancer'], answer:'writer', hint:'📜' },
  { id:91, level:'advanced', type:'fill', question:'💡 Edison ___ the light bulb', options:['destroyed','invented','sold','borrowed'], answer:'invented', hint:'🔦' },
  { id:92, level:'advanced', type:'fill', question:'🌐 The ___ connects people worldwide', options:['radio','television','internet','phone'], answer:'internet', hint:'💻' },
  { id:93, level:'advanced', type:'fill', question:'🎯 To ___ is to reach your goal', options:['fail','succeed','lose','give up'], answer:'succeed', hint:'🏆' },
  { id:94, level:'advanced', type:'fill', question:'📖 Reading ___ your vocabulary', options:['reduces','improves','destroys','limits'], answer:'improves', hint:'📚' },
  { id:95, level:'advanced', type:'fill', question:'🤝 A good leader ___ people', options:['ignores','inspires','scares','controls'], answer:'inspires', hint:'✨' },

  // More unscramble beginner
  { id:96, level:'beginner', type:'unscramble', scrambled:'NIAR', answer:'RAIN', hint:'🌧️ Gökden ýagýar', tk:'ýagyş', ru:'дождь' },
  { id:97, level:'beginner', type:'unscramble', scrambled:'OWNS', answer:'SNOW', hint:'❄️ Ak we sowuk', tk:'gar', ru:'снег' },
  { id:98, level:'beginner', type:'unscramble', scrambled:'RIWE', answer:'WIRE', hint:'🔌 Elektrik geçiriji', tk:'sim', ru:'провод' },
  { id:99, level:'beginner', type:'unscramble', scrambled:'NAFL', answer:'FLAN', hint:'🥧 Tagam görnüşi', tk:'tagam', ru:'флан' },
  { id:100, level:'beginner', type:'unscramble', scrambled:'ARET', answer:'TEAR', hint:'😢 Aglanda çykýar', tk:'göz ýaşy', ru:'слеза' },
  { id:101, level:'intermediate', type:'unscramble', scrambled:'ECSPAS', answer:'SPACES', hint:'🌌 Boşluklar', tk:'boşluklar', ru:'пространства' },
  { id:102, level:'intermediate', type:'unscramble', scrambled:'GLENAR', answer:'GARLEN', hint:'🧅 Tagam beriji', tk:'sarymsak', ru:'чеснок' },
  { id:103, level:'intermediate', type:'unscramble', scrambled:'CARMED', answer:'CREAMED', hint:'🥛 Gatyk ýaly', tk:'gaýmak', ru:'сливки' },
  { id:104, level:'intermediate', type:'unscramble', scrambled:'SPLAEH', answer:'PLEASE', hint:'🙏 Haýyş etmek', tk:'haýyş', ru:'пожалуйста' },
  { id:105, level:'intermediate', type:'unscramble', scrambled:'MOSTRA', answer:'MANSTR', hint:'Monster? Closer...', tk:'...', ru:'...' },
  { id:106, level:'advanced', type:'unscramble', scrambled:'YTIVITCRE', answer:'CREATIVITY', hint:'🎨 Döredijilik ukyby', tk:'döredijilik', ru:'творчество' },
  { id:107, level:'advanced', type:'unscramble', scrambled:'YCLAIDIPSIN', answer:'DISCIPLINE', hint:'📏 Düzgün-nyzam', tk:'tertip-nyzam', ru:'дисциплина' },
  { id:108, level:'advanced', type:'unscramble', scrambled:'YTIRUCES', answer:'SECURITY', hint:'🔒 Howpsuzlyk', tk:'howpsuzlyk', ru:'безопасность' },
  { id:109, level:'advanced', type:'unscramble', scrambled:'YTIDOMMUC', answer:'COMMUNITY', hint:'👥 Jemgyýet', tk:'jemgyýet', ru:'сообщество' },
  { id:110, level:'advanced', type:'unscramble', scrambled:'YTICAPAC', answer:'CAPACITY', hint:'📦 Kuwwat, mümkinçilik', tk:'kuwwat', ru:'вместимость' },
];
