// 120+ test soraglary
export const TESTS = [
  // BEGINNER - Başlangyç (1-40)
  { id:1, level:'beginner', en:'What is "pişik" in English?', options:['cat','dog','bird','fish'], answer:'cat' },
  { id:2, level:'beginner', en:'What is "it" in English?', options:['cat','dog','bird','fish'], answer:'dog' },
  { id:3, level:'beginner', en:'How do you say "suw" in English?', options:['milk','water','tea','juice'], answer:'water' },
  { id:4, level:'beginner', en:'What is "gyzyl" in English?', options:['blue','green','red','yellow'], answer:'red' },
  { id:5, level:'beginner', en:'What does "bir" mean?', options:['one','two','three','four'], answer:'one' },
  { id:6, level:'beginner', en:'What is "ene" in English?', options:['father','sister','mother','brother'], answer:'mother' },
  { id:7, level:'beginner', en:'"Çörek" means...', options:['bread','water','milk','egg'], answer:'bread' },
  { id:8, level:'beginner', en:'How do you say "gün" in English?', options:['moon','star','sun','cloud'], answer:'sun' },
  { id:9, level:'beginner', en:'What is "öý" in English?', options:['school','house','market','park'], answer:'house' },
  { id:10, level:'beginner', en:'"Maşyn" means...', options:['bus','car','train','plane'], answer:'car' },
  { id:11, level:'beginner', en:'What is "gök" in English?', options:['blue','red','green','yellow'], answer:'blue' },
  { id:12, level:'beginner', en:'How do you say "baş" in English?', options:['foot','hand','head','eye'], answer:'head' },
  { id:13, level:'beginner', en:'"Uly" means...', options:['small','big','tall','short'], answer:'big' },
  { id:14, level:'beginner', en:'What is "kitap" in English?', options:['book','pen','pencil','desk'], answer:'book' },
  { id:15, level:'beginner', en:'How do you say "ýaşyl" in English?', options:['blue','red','green','yellow'], answer:'green' },
  { id:16, level:'beginner', en:'"Gury" means...', options:['hot','cold','warm','cool'], answer:'cold' },
  { id:17, level:'beginner', en:'What is "agaç" in English?', options:['flower','grass','tree','stone'], answer:'tree' },
  { id:18, level:'beginner', en:'"Okamak" means...', options:['write','read','speak','listen'], answer:'read' },
  { id:19, level:'beginner', en:'What is "dost" in English?', options:['enemy','friend','teacher','student'], answer:'friend' },
  { id:20, level:'beginner', en:'How do you say "uçar" in English?', options:['bus','train','plane','ship'], answer:'plane' },
  { id:21, level:'beginner', en:'"Sary" means...', options:['blue','green','red','yellow'], answer:'yellow' },
  { id:22, level:'beginner', en:'What is "iki" in English?', options:['one','two','three','four'], answer:'two' },
  { id:23, level:'beginner', en:'"Süýt" means...', options:['water','tea','milk','coffee'], answer:'milk' },
  { id:24, level:'beginner', en:'What is "alma" in English?', options:['orange','apple','banana','grape'], answer:'apple' },
  { id:25, level:'beginner', en:'How do you say "göz" in English?', options:['nose','mouth','eye','ear'], answer:'eye' },
  { id:26, level:'beginner', en:'"Mugallym" means...', options:['student','teacher','doctor','engineer'], answer:'teacher' },
  { id:27, level:'beginner', en:'What is "ýol" in English?', options:['road','park','market','school'], answer:'road' },
  { id:28, level:'beginner', en:'"Gowy" means...', options:['bad','good','ugly','dark'], answer:'good' },
  { id:29, level:'beginner', en:'What is "gapy" in English?', options:['window','door','wall','floor'], answer:'door' },
  { id:30, level:'beginner', en:'How do you say "ýagyş" in English?', options:['snow','wind','rain','cloud'], answer:'rain' },
  { id:31, level:'beginner', en:'"Aýdym" means...', options:['dance','song','music','play'], answer:'song' },
  { id:32, level:'beginner', en:'What is "çaý" in English?', options:['water','coffee','tea','milk'], answer:'tea' },
  { id:33, level:'beginner', en:'"Gitmek" means...', options:['come','go','run','walk'], answer:'go' },
  { id:34, level:'beginner', en:'What is "köçe" in English?', options:['road','street','park','city'], answer:'street' },
  { id:35, level:'beginner', en:'"Salam" means...', options:['goodbye','hello','sorry','thanks'], answer:'hello' },
  { id:36, level:'beginner', en:'What is "pul" in English?', options:['price','money','bank','pay'], answer:'money' },
  { id:37, level:'beginner', en:'"Suw" means...', options:['fire','earth','air','water'], answer:'water' },
  { id:38, level:'beginner', en:'What is "gülmek" in English?', options:['cry','laugh','sing','dance'], answer:'laugh' },
  { id:39, level:'beginner', en:'"Ýatlamak" means...', options:['forget','remember','know','think'], answer:'remember' },
  { id:40, level:'beginner', en:'What is "söýmek" in English?', options:['hate','like','love','want'], answer:'love' },

  // INTERMEDIATE (41-80)
  { id:41, level:'intermediate', en:'What is "hassahana" in English?', options:['pharmacy','hospital','clinic','school'], answer:'hospital' },
  { id:42, level:'intermediate', en:'"Syýahat etmek" means...', options:['study','travel','work','play'], answer:'travel' },
  { id:43, level:'intermediate', en:'What is "ykdysadyýet" in English?', options:['politics','science','economics','history'], answer:'economics' },
  { id:44, level:'intermediate', en:'"Täsir" means...', options:['result','effect','cause','reason'], answer:'effect' },
  { id:45, level:'intermediate', en:'What is "howpsuz" in English?', options:['dangerous','safe','free','strong'], answer:'safe' },
  { id:46, level:'intermediate', en:'"Mümkinçilik" means...', options:['problem','risk','opportunity','challenge'], answer:'opportunity' },
  { id:47, level:'intermediate', en:'What is "düşündirmek" in English?', options:['ask','explain','answer','question'], answer:'explain' },
  { id:48, level:'intermediate', en:'"Arassa" means...', options:['dirty','clean','dry','wet'], answer:'clean' },
  { id:49, level:'intermediate', en:'What is "garaşmak" in English?', options:['wait','work','walk','watch'], answer:'wait' },
  { id:50, level:'intermediate', en:'"Tejribe" means...', options:['knowledge','experience','skill','ability'], answer:'experience' },
  { id:51, level:'intermediate', en:'What is "üstünlik" in English?', options:['failure','problem','success','challenge'], answer:'success' },
  { id:52, level:'intermediate', en:'"Öwrenmek" means...', options:['teach','study','learn','know'], answer:'learn' },
  { id:53, level:'intermediate', en:'What is "meşhur" in English?', options:['ugly','rich','famous','poor'], answer:'famous' },
  { id:54, level:'intermediate', en:'"Howp" means...', options:['safety','danger','risk','chance'], answer:'danger' },
  { id:55, level:'intermediate', en:'What is "adalat" in English?', options:['peace','justice','freedom','law'], answer:'justice' },
  { id:56, level:'intermediate', en:'"Döretmek" means...', options:['destroy','build','create','break'], answer:'create' },
  { id:57, level:'intermediate', en:'What is "goldaw" in English?', options:['attack','support','ignore','avoid'], answer:'support' },
  { id:58, level:'intermediate', en:'"Artdyrmak" means...', options:['decrease','reduce','increase','remove'], answer:'increase' },
  { id:59, level:'intermediate', en:'What is "karar bermek" in English?', options:['suggest','decide','agree','refuse'], answer:'decide' },
  { id:60, level:'intermediate', en:'"Ýeňmek" means...', options:['lose','draw','win','play'], answer:'win' },
  { id:61, level:'intermediate', en:'What is "parahatçylyk" in English?', options:['war','freedom','peace','justice'], answer:'peace' },
  { id:62, level:'intermediate', en:'"Hormat" means...', options:['disrespect','respect','hate','love'], answer:'respect' },
  { id:63, level:'intermediate', en:'What is "bagtly" in English?', options:['sad','angry','happy','tired'], answer:'happy' },
  { id:64, level:'intermediate', en:'"Güýçli" means...', options:['weak','strong','slow','fast'], answer:'strong' },
  { id:65, level:'intermediate', en:'What is "maglumat" in English?', options:['news','information','message','data'], answer:'information' },
  { id:66, level:'intermediate', en:'"Geçmiş" means...', options:['future','present','past','now'], answer:'past' },
  { id:67, level:'intermediate', en:'What is "geljek" in English?', options:['past','present','future','now'], answer:'future' },
  { id:68, level:'intermediate', en:'"Maslahat" means...', options:['order','advice','command','request'], answer:'advice' },
  { id:69, level:'intermediate', en:'What is "azat" in English?', options:['slave','free','poor','rich'], answer:'free' },
  { id:70, level:'intermediate', en:'"Tizlik" means...', options:['time','speed','force','power'], answer:'speed' },
  { id:71, level:'intermediate', en:'What is "uly" in English?', options:['small','tiny','big','short'], answer:'big' },
  { id:72, level:'intermediate', en:'"Özüni alyp baryş" means...', options:['character','behavior','attitude','personality'], answer:'behavior' },
  { id:73, level:'intermediate', en:'What is "aýdyň" in English?', options:['dark','unclear','clear','hidden'], answer:'clear' },
  { id:74, level:'intermediate', en:'"Köplenç" means...', options:['rarely','never','always','often'], answer:'often' },
  { id:75, level:'intermediate', en:'What is "üns" in English?', options:['interest','attention','focus','care'], answer:'attention' },
  { id:76, level:'intermediate', en:'"Aňsat" means...', options:['hard','difficult','easy','complex'], answer:'easy' },
  { id:77, level:'intermediate', en:'What is "söwda" in English?', options:['travel','industry','trade','business'], answer:'trade' },
  { id:78, level:'intermediate', en:'"Ösüş" means...', options:['decline','progress','failure','problem'], answer:'progress' },
  { id:79, level:'intermediate', en:'What is "zerur" in English?', options:['optional','extra','necessary','additional'], answer:'necessary' },
  { id:80, level:'intermediate', en:'"Paýlaşmak" means...', options:['keep','hide','share','store'], answer:'share' },

  // ADVANCED (81-120)
  { id:81, level:'advanced', en:'What is "garaşsyzlyk" in English?', options:['freedom','peace','independence','democracy'], answer:'independence' },
  { id:82, level:'advanced', en:'"Demokratiýa" means...', options:['monarchy','dictatorship','democracy','republic'], answer:'democracy' },
  { id:83, level:'advanced', en:'What is "edermenlik" in English?', options:['wisdom','patience','courage','kindness'], answer:'courage' },
  { id:84, level:'advanced', en:'"Jogapkärçilik" means...', options:['freedom','responsibility','authority','power'], answer:'responsibility' },
  { id:85, level:'advanced', en:'What is "medeniýet" in English?', options:['religion','tradition','culture','history'], answer:'culture' },
  { id:86, level:'advanced', en:'"Adalatly" means...', options:['unfair','unjust','fair','biased'], answer:'fair' },
  { id:87, level:'advanced', en:'What is "çözgüt" in English?', options:['problem','question','solution','decision'], answer:'solution' },
  { id:88, level:'advanced', en:'"Aragatnaşyk" means...', options:['silence','communication','isolation','argument'], answer:'communication' },
  { id:89, level:'advanced', en:'What is "hakykat" in English?', options:['lie','myth','truth','story'], answer:'truth' },
  { id:90, level:'advanced', en:'"Paýhas" means...', options:['knowledge','wisdom','intelligence','memory'], answer:'wisdom' },
  { id:91, level:'advanced', en:'What is "ynаnmak" in English?', options:['doubt','trust','fear','hate'], answer:'trust' },
  { id:92, level:'advanced', en:'"Döredijilik" means...', options:['destruction','creativity','imagination','fantasy'], answer:'creativity' },
  { id:93, level:'advanced', en:'What is "ulgam" in English?', options:['method','process','system','pattern'], answer:'system' },
  { id:94, level:'advanced', en:'"Häkimiýet" means...', options:['freedom','authority','justice','law'], answer:'authority' },
  { id:95, level:'advanced', en:'What is "nesil" in English?', options:['family','group','generation','society'], answer:'generation' },
  { id:96, level:'advanced', en:'"Ýeňip geçmek" means...', options:['fail','surrender','overcome','avoid'], answer:'overcome' },
  { id:97, level:'advanced', en:'What is "bäsleşik" in English?', options:['cooperation','harmony','competition','agreement'], answer:'competition' },
  { id:98, level:'advanced', en:'"Goşant" means...', options:['loss','debt','contribution','investment'], answer:'contribution' },
  { id:99, level:'advanced', en:'What is "jemgyýet" in English?', options:['family','nation','society','community'], answer:'community' },
  { id:100, level:'advanced', en:'"Ynamlylyk" means...', options:['doubt','fear','confidence','courage'], answer:'confidence' },
  { id:101, level:'advanced', en:'What is "ýolbaşçylyk" in English?', options:['followership','membership','leadership','friendship'], answer:'leadership' },
  { id:102, level:'advanced', en:'"Tapawut" means...', options:['similarity','equality','difference','comparison'], answer:'difference' },
  { id:103, level:'advanced', en:'What is "täsir etmek" in English?', options:['ignore','support','affect','protect'], answer:'affect' },
  { id:104, level:'advanced', en:'"Subut etmek" means...', options:['deny','assume','prove','guess'], answer:'prove' },
  { id:105, level:'advanced', en:'What is "üpjün etmek" in English?', options:['demand','request','provide','ask'], answer:'provide' },
  { id:106, level:'advanced', en:'"Ýaýramak" means...', options:['collect','gather','spread','concentrate'], answer:'spread' },
  { id:107, level:'advanced', en:'What is "deňagramlylyk" in English?', options:['chaos','disorder','balance','conflict'], answer:'balance' },
  { id:108, level:'advanced', en:'"Tassyklamak" means...', options:['deny','reject','confirm','refuse'], answer:'confirm' },
  { id:109, level:'advanced', en:'What is "özüne çekmek" in English?', options:['repel','ignore','attract','avoid'], answer:'attract' },
  { id:110, level:'advanced', en:'"Raýat" means...', options:['soldier','foreigner','citizen','tourist'], answer:'citizen' },
  { id:111, level:'advanced', en:'What is "ykdysadyýet" in English?', options:['politics','science','economics','sociology'], answer:'economics' },
  { id:112, level:'advanced', en:'"Pikiir alyşma" means...', options:['argument','silence','discussion','fight'], answer:'discussion' },
  { id:113, level:'advanced', en:'What is "salgyt" in English?', options:['income','salary','tax','fine'], answer:'tax' },
  { id:114, level:'advanced', en:'"Uýgunlaşmak" means...', options:['resist','change','adapt','transform'], answer:'adapt' },
  { id:115, level:'advanced', en:'What is "hyýal" in English?', options:['reality','fact','imagination','memory'], answer:'imagination' },
  { id:116, level:'advanced', en:'"Ýetmezçilik" means...', options:['surplus','excess','lack','plenty'], answer:'lack' },
  { id:117, level:'advanced', en:'What is "emeli hemra" in English?', options:['rocket','meteor','satellite','comet'], answer:'satellite' },
  { id:118, level:'advanced', en:'"Filosofiýa" means...', options:['science','art','philosophy','psychology'], answer:'philosophy' },
  { id:119, level:'advanced', en:'What is "rewolýusiýa" in English?', options:['evolution','invention','revolution','discovery'], answer:'revolution' },
  { id:120, level:'advanced', en:'"Ylmy iş" means...', options:['experiment','invention','research','study'], answer:'research' },

  // GRAMMAR TESTS (121-130)
  { id:121, level:'beginner', en:'Choose the correct sentence:', options:['I is happy','I are happy','I am happy','I be happy'], answer:'I am happy' },
  { id:122, level:'beginner', en:'Choose the correct form:', options:['She go to school','She goes to school','She going to school','She gone to school'], answer:'She goes to school' },
  { id:123, level:'intermediate', en:'Past tense of "go":', options:['goed','went','gone','going'], answer:'went' },
  { id:124, level:'intermediate', en:'Past tense of "eat":', options:['eated','ated','ate','eaten'], answer:'ate' },
  { id:125, level:'intermediate', en:'Choose correct: "There ___ many people"', options:['is','am','are','be'], answer:'are' },
  { id:126, level:'advanced', en:'"If I ___ rich, I would travel"', options:['am','were','was','be'], answer:'were' },
  { id:127, level:'advanced', en:'Passive voice: "The book ___ written"', options:['is','are','was','were'], answer:'was' },
  { id:128, level:'intermediate', en:'Plural of "child":', options:['childs','children','childes','child'], answer:'children' },
  { id:129, level:'intermediate', en:'Plural of "mouse":', options:['mouses','mices','mice','mouse'], answer:'mice' },
  { id:130, level:'advanced', en:'Choose correct: "I ___ here for 2 hours"', options:['am','was','have been','had been'], answer:'have been' },
];
