// 1000+ söz sözlügi — Iňlis, Rus, Türkmen
export const WORDS = [
  // ANIMALS - Haýwanlar
  { id:1, en:'cat', ru:'кошка', tk:'pişik', category:'animals', level:'beginner' },
  { id:2, en:'dog', ru:'собака', tk:'it', category:'animals', level:'beginner' },
  { id:3, en:'bird', ru:'птица', tk:'guş', category:'animals', level:'beginner' },
  { id:4, en:'fish', ru:'рыба', tk:'balyk', category:'animals', level:'beginner' },
  { id:5, en:'horse', ru:'лошадь', tk:'at', category:'animals', level:'beginner' },
  { id:6, en:'cow', ru:'корова', tk:'sygyr', category:'animals', level:'beginner' },
  { id:7, en:'sheep', ru:'овца', tk:'goýun', category:'animals', level:'beginner' },
  { id:8, en:'goat', ru:'коза', tk:'geçi', category:'animals', level:'beginner' },
  { id:9, en:'chicken', ru:'курица', tk:'towuk', category:'animals', level:'beginner' },
  { id:10, en:'lion', ru:'лев', tk:'arslan', category:'animals', level:'beginner' },
  { id:11, en:'tiger', ru:'тигр', tk:'gaplaň', category:'animals', level:'beginner' },
  { id:12, en:'elephant', ru:'слон', tk:'pil', category:'animals', level:'beginner' },
  { id:13, en:'bear', ru:'медведь', tk:'aýy', category:'animals', level:'beginner' },
  { id:14, en:'wolf', ru:'волк', tk:'möjek', category:'animals', level:'beginner' },
  { id:15, en:'fox', ru:'лиса', tk:'tilki', category:'animals', level:'beginner' },
  { id:16, en:'rabbit', ru:'кролик', tk:'towşan', category:'animals', level:'beginner' },
  { id:17, en:'monkey', ru:'обезьяна', tk:'maýmyn', category:'animals', level:'beginner' },
  { id:18, en:'snake', ru:'змея', tk:'ýylan', category:'animals', level:'beginner' },
  { id:19, en:'camel', ru:'верблюд', tk:'düýe', category:'animals', level:'beginner' },
  { id:20, en:'donkey', ru:'осёл', tk:'eşek', category:'animals', level:'beginner' },
  { id:21, en:'duck', ru:'утка', tk:'ördek', category:'animals', level:'beginner' },
  { id:22, en:'eagle', ru:'орёл', tk:'bürgüt', category:'animals', level:'intermediate' },
  { id:23, en:'deer', ru:'олень', tk:'keýik', category:'animals', level:'intermediate' },
  { id:24, en:'crocodile', ru:'крокодил', tk:'krokodil', category:'animals', level:'intermediate' },
  { id:25, en:'giraffe', ru:'жираф', tk:'žiraf', category:'animals', level:'intermediate' },

  // FOOD - Iýmit
  { id:26, en:'bread', ru:'хлеб', tk:'çörek', category:'food', level:'beginner' },
  { id:27, en:'water', ru:'вода', tk:'suw', category:'food', level:'beginner' },
  { id:28, en:'milk', ru:'молоко', tk:'süýt', category:'food', level:'beginner' },
  { id:29, en:'meat', ru:'мясо', tk:'et', category:'food', level:'beginner' },
  { id:30, en:'egg', ru:'яйцо', tk:'ýumurtga', category:'food', level:'beginner' },
  { id:31, en:'rice', ru:'рис', tk:'tüwi', category:'food', level:'beginner' },
  { id:32, en:'apple', ru:'яблоко', tk:'alma', category:'food', level:'beginner' },
  { id:33, en:'orange', ru:'апельсин', tk:'apelsin', category:'food', level:'beginner' },
  { id:34, en:'banana', ru:'банан', tk:'banan', category:'food', level:'beginner' },
  { id:35, en:'tomato', ru:'помидор', tk:'pomidor', category:'food', level:'beginner' },
  { id:36, en:'potato', ru:'картошка', tk:'kartoşka', category:'food', level:'beginner' },
  { id:37, en:'onion', ru:'лук', tk:'sogan', category:'food', level:'beginner' },
  { id:38, en:'garlic', ru:'чеснок', tk:'sarymsak', category:'food', level:'beginner' },
  { id:39, en:'sugar', ru:'сахар', tk:'şeker', category:'food', level:'beginner' },
  { id:40, en:'salt', ru:'соль', tk:'duz', category:'food', level:'beginner' },
  { id:41, en:'oil', ru:'масло', tk:'ýag', category:'food', level:'beginner' },
  { id:42, en:'cheese', ru:'сыр', tk:'peýnir', category:'food', level:'beginner' },
  { id:43, en:'butter', ru:'масло', tk:'ýaj', category:'food', level:'beginner' },
  { id:44, en:'tea', ru:'чай', tk:'çaý', category:'food', level:'beginner' },
  { id:45, en:'coffee', ru:'кофе', tk:'kofe', category:'food', level:'beginner' },
  { id:46, en:'soup', ru:'суп', tk:'çorba', category:'food', level:'beginner' },
  { id:47, en:'fish', ru:'рыба', tk:'balyk', category:'food', level:'beginner' },
  { id:48, en:'grape', ru:'виноград', tk:'üzüm', category:'food', level:'beginner' },
  { id:49, en:'melon', ru:'дыня', tk:'gawun', category:'food', level:'beginner' },
  { id:50, en:'watermelon', ru:'арбуз', tk:'garpyz', category:'food', level:'beginner' },
  { id:51, en:'strawberry', ru:'клубника', tk:'ýertudana', category:'food', level:'intermediate' },
  { id:52, en:'lemon', ru:'лимон', tk:'limon', category:'food', level:'beginner' },
  { id:53, en:'pear', ru:'груша', tk:'armyt', category:'food', level:'beginner' },
  { id:54, en:'peach', ru:'персик', tk:'şetdaly', category:'food', level:'beginner' },
  { id:55, en:'cucumber', ru:'огурец', tk:'hyýar', category:'food', level:'beginner' },
  { id:56, en:'carrot', ru:'морковь', tk:'käşir', category:'food', level:'beginner' },
  { id:57, en:'cabbage', ru:'капуста', tk:'kelem', category:'food', level:'beginner' },
  { id:58, en:'pepper', ru:'перец', tk:'burç', category:'food', level:'beginner' },
  { id:59, en:'mushroom', ru:'гриб', tk:'kömelek', category:'food', level:'intermediate' },
  { id:60, en:'honey', ru:'мёд', tk:'bal', category:'food', level:'beginner' },

  // COLORS - Reňkler
  { id:61, en:'red', ru:'красный', tk:'gyzyl', category:'colors', level:'beginner' },
  { id:62, en:'blue', ru:'синий', tk:'gök', category:'colors', level:'beginner' },
  { id:63, en:'green', ru:'зелёный', tk:'ýaşyl', category:'colors', level:'beginner' },
  { id:64, en:'yellow', ru:'жёлтый', tk:'sary', category:'colors', level:'beginner' },
  { id:65, en:'white', ru:'белый', tk:'ak', category:'colors', level:'beginner' },
  { id:66, en:'black', ru:'чёрный', tk:'gara', category:'colors', level:'beginner' },
  { id:67, en:'orange', ru:'оранжевый', tk:'mämişi', category:'colors', level:'beginner' },
  { id:68, en:'purple', ru:'фиолетовый', tk:'melewşe', category:'colors', level:'beginner' },
  { id:69, en:'pink', ru:'розовый', tk:'gülgüne', category:'colors', level:'beginner' },
  { id:70, en:'brown', ru:'коричневый', tk:'goňur', category:'colors', level:'beginner' },
  { id:71, en:'grey', ru:'серый', tk:'çal', category:'colors', level:'beginner' },
  { id:72, en:'gold', ru:'золотой', tk:'altyn', category:'colors', level:'intermediate' },
  { id:73, en:'silver', ru:'серебряный', tk:'kümüş', category:'colors', level:'intermediate' },

  // NUMBERS - Sanlar
  { id:74, en:'one', ru:'один', tk:'bir', category:'numbers', level:'beginner' },
  { id:75, en:'two', ru:'два', tk:'iki', category:'numbers', level:'beginner' },
  { id:76, en:'three', ru:'три', tk:'üç', category:'numbers', level:'beginner' },
  { id:77, en:'four', ru:'четыре', tk:'dört', category:'numbers', level:'beginner' },
  { id:78, en:'five', ru:'пять', tk:'bäş', category:'numbers', level:'beginner' },
  { id:79, en:'six', ru:'шесть', tk:'alty', category:'numbers', level:'beginner' },
  { id:80, en:'seven', ru:'семь', tk:'ýedi', category:'numbers', level:'beginner' },
  { id:81, en:'eight', ru:'восемь', tk:'sekiz', category:'numbers', level:'beginner' },
  { id:82, en:'nine', ru:'девять', tk:'dokuz', category:'numbers', level:'beginner' },
  { id:83, en:'ten', ru:'десять', tk:'on', category:'numbers', level:'beginner' },
  { id:84, en:'twenty', ru:'двадцать', tk:'ýigrimi', category:'numbers', level:'beginner' },
  { id:85, en:'hundred', ru:'сто', tk:'ýüz', category:'numbers', level:'beginner' },
  { id:86, en:'thousand', ru:'тысяча', tk:'müň', category:'numbers', level:'beginner' },
  { id:87, en:'million', ru:'миллион', tk:'million', category:'numbers', level:'intermediate' },

  // FAMILY - Maşgala
  { id:88, en:'mother', ru:'мать', tk:'ene', category:'family', level:'beginner' },
  { id:89, en:'father', ru:'отец', tk:'ata', category:'family', level:'beginner' },
  { id:90, en:'sister', ru:'сестра', tk:'uýa', category:'family', level:'beginner' },
  { id:91, en:'brother', ru:'брат', tk:'dogan', category:'family', level:'beginner' },
  { id:92, en:'grandmother', ru:'бабушка', tk:'ene', category:'family', level:'beginner' },
  { id:93, en:'grandfather', ru:'дедушка', tk:'ata', category:'family', level:'beginner' },
  { id:94, en:'son', ru:'сын', tk:'ogul', category:'family', level:'beginner' },
  { id:95, en:'daughter', ru:'дочь', tk:'gyz', category:'family', level:'beginner' },
  { id:96, en:'husband', ru:'муж', tk:'är', category:'family', level:'beginner' },
  { id:97, en:'wife', ru:'жена', tk:'aýal', category:'family', level:'beginner' },
  { id:98, en:'uncle', ru:'дядя', tk:'daýy', category:'family', level:'beginner' },
  { id:99, en:'aunt', ru:'тётя', tk:'daýza', category:'family', level:'beginner' },
  { id:100, en:'cousin', ru:'двоюродный', tk:'ýegen', category:'family', level:'intermediate' },

  // BODY - Beden
  { id:101, en:'head', ru:'голова', tk:'baş', category:'body', level:'beginner' },
  { id:102, en:'eye', ru:'глаз', tk:'göz', category:'body', level:'beginner' },
  { id:103, en:'nose', ru:'нос', tk:'burun', category:'body', level:'beginner' },
  { id:104, en:'mouth', ru:'рот', tk:'agyz', category:'body', level:'beginner' },
  { id:105, en:'ear', ru:'ухо', tk:'gulak', category:'body', level:'beginner' },
  { id:106, en:'hand', ru:'рука', tk:'el', category:'body', level:'beginner' },
  { id:107, en:'foot', ru:'нога', tk:'aýak', category:'body', level:'beginner' },
  { id:108, en:'heart', ru:'сердце', tk:'ýürek', category:'body', level:'beginner' },
  { id:109, en:'hair', ru:'волосы', tk:'saç', category:'body', level:'beginner' },
  { id:110, en:'tooth', ru:'зуб', tk:'diş', category:'body', level:'beginner' },
  { id:111, en:'tongue', ru:'язык', tk:'dil', category:'body', level:'beginner' },
  { id:112, en:'finger', ru:'палец', tk:'barmak', category:'body', level:'beginner' },
  { id:113, en:'back', ru:'спина', tk:'arka', category:'body', level:'beginner' },
  { id:114, en:'stomach', ru:'живот', tk:'garyn', category:'body', level:'beginner' },
  { id:115, en:'shoulder', ru:'плечо', tk:'egni', category:'body', level:'intermediate' },

  // HOUSE - Öý
  { id:116, en:'house', ru:'дом', tk:'öý', category:'house', level:'beginner' },
  { id:117, en:'room', ru:'комната', tk:'otag', category:'house', level:'beginner' },
  { id:118, en:'door', ru:'дверь', tk:'gapy', category:'house', level:'beginner' },
  { id:119, en:'window', ru:'окно', tk:'penjire', category:'house', level:'beginner' },
  { id:120, en:'table', ru:'стол', tk:'stol', category:'house', level:'beginner' },
  { id:121, en:'chair', ru:'стул', tk:'oturgyç', category:'house', level:'beginner' },
  { id:122, en:'bed', ru:'кровать', tk:'düşek', category:'house', level:'beginner' },
  { id:123, en:'kitchen', ru:'кухня', tk:'aşhana', category:'house', level:'beginner' },
  { id:124, en:'bathroom', ru:'ванная', tk:'hammam', category:'house', level:'beginner' },
  { id:125, en:'floor', ru:'пол', tk:'pол', category:'house', level:'beginner' },
  { id:126, en:'wall', ru:'стена', tk:'diwar', category:'house', level:'beginner' },
  { id:127, en:'ceiling', ru:'потолок', tk:'potoлок', category:'house', level:'intermediate' },
  { id:128, en:'roof', ru:'крыша', tk:'üçek', category:'house', level:'beginner' },
  { id:129, en:'garden', ru:'сад', tk:'bagy', category:'house', level:'beginner' },
  { id:130, en:'stairs', ru:'лестница', tk:'basgançak', category:'house', level:'intermediate' },

  // NATURE - Tebigat
  { id:131, en:'sun', ru:'солнце', tk:'gün', category:'nature', level:'beginner' },
  { id:132, en:'moon', ru:'луна', tk:'Aý', category:'nature', level:'beginner' },
  { id:133, en:'star', ru:'звезда', tk:'ýyldyz', category:'nature', level:'beginner' },
  { id:134, en:'sky', ru:'небо', tk:'asman', category:'nature', level:'beginner' },
  { id:135, en:'cloud', ru:'облако', tk:'bulut', category:'nature', level:'beginner' },
  { id:136, en:'rain', ru:'дождь', tk:'ýagyş', category:'nature', level:'beginner' },
  { id:137, en:'snow', ru:'снег', tk:'gar', category:'nature', level:'beginner' },
  { id:138, en:'wind', ru:'ветер', tk:'ýel', category:'nature', level:'beginner' },
  { id:139, en:'river', ru:'река', tk:'derýa', category:'nature', level:'beginner' },
  { id:140, en:'sea', ru:'море', tk:'deňiz', category:'nature', level:'beginner' },
  { id:141, en:'mountain', ru:'гора', tk:'dag', category:'nature', level:'beginner' },
  { id:142, en:'forest', ru:'лес', tk:'tokaý', category:'nature', level:'beginner' },
  { id:143, en:'desert', ru:'пустыня', tk:'çöl', category:'nature', level:'beginner' },
  { id:144, en:'flower', ru:'цветок', tk:'gül', category:'nature', level:'beginner' },
  { id:145, en:'tree', ru:'дерево', tk:'agaç', category:'nature', level:'beginner' },
  { id:146, en:'grass', ru:'трава', tk:'ot', category:'nature', level:'beginner' },
  { id:147, en:'stone', ru:'камень', tk:'daş', category:'nature', level:'beginner' },
  { id:148, en:'sand', ru:'песок', tk:'çäge', category:'nature', level:'beginner' },
  { id:149, en:'fire', ru:'огонь', tk:'ot', category:'nature', level:'beginner' },
  { id:150, en:'ice', ru:'лёд', tk:'buz', category:'nature', level:'beginner' },

  // TRANSPORT - Ulag
  { id:151, en:'car', ru:'машина', tk:'maşyn', category:'transport', level:'beginner' },
  { id:152, en:'bus', ru:'автобус', tk:'awtobus', category:'transport', level:'beginner' },
  { id:153, en:'train', ru:'поезд', tk:'otly', category:'transport', level:'beginner' },
  { id:154, en:'plane', ru:'самолёт', tk:'uçar', category:'transport', level:'beginner' },
  { id:155, en:'ship', ru:'корабль', tk:'gämi', category:'transport', level:'beginner' },
  { id:156, en:'bicycle', ru:'велосипед', tk:'welosiped', category:'transport', level:'beginner' },
  { id:157, en:'taxi', ru:'такси', tk:'taksi', category:'transport', level:'beginner' },
  { id:158, en:'truck', ru:'грузовик', tk:'ýük maşyny', category:'transport', level:'intermediate' },
  { id:159, en:'motorcycle', ru:'мотоцикл', tk:'motosikl', category:'transport', level:'intermediate' },
  { id:160, en:'helicopter', ru:'вертолёт', tk:'dikuçar', category:'transport', level:'intermediate' },

  // SCHOOL - Mekdep
  { id:161, en:'school', ru:'школа', tk:'mekdep', category:'school', level:'beginner' },
  { id:162, en:'teacher', ru:'учитель', tk:'mugallym', category:'school', level:'beginner' },
  { id:163, en:'student', ru:'ученик', tk:'okuwçy', category:'school', level:'beginner' },
  { id:164, en:'book', ru:'книга', tk:'kitap', category:'school', level:'beginner' },
  { id:165, en:'pen', ru:'ручка', tk:'ruçka', category:'school', level:'beginner' },
  { id:166, en:'pencil', ru:'карандаш', tk:'galam', category:'school', level:'beginner' },
  { id:167, en:'notebook', ru:'тетрадь', tk:'depder', category:'school', level:'beginner' },
  { id:168, en:'desk', ru:'парта', tk:'parta', category:'school', level:'beginner' },
  { id:169, en:'board', ru:'доска', tk:'tagta', category:'school', level:'beginner' },
  { id:170, en:'lesson', ru:'урок', tk:'sapak', category:'school', level:'beginner' },
  { id:171, en:'homework', ru:'домашнее задание', tk:'öý işi', category:'school', level:'beginner' },
  { id:172, en:'exam', ru:'экзамен', tk:'synagdan', category:'school', level:'intermediate' },
  { id:173, en:'library', ru:'библиотека', tk:'kitaphana', category:'school', level:'intermediate' },
  { id:174, en:'university', ru:'университет', tk:'uniwersitet', category:'school', level:'intermediate' },
  { id:175, en:'dictionary', ru:'словарь', tk:'sözlük', category:'school', level:'intermediate' },

  // CLOTHES - Egin-eşik
  { id:176, en:'shirt', ru:'рубашка', tk:'köýnek', category:'clothes', level:'beginner' },
  { id:177, en:'trousers', ru:'брюки', tk:'balak', category:'clothes', level:'beginner' },
  { id:178, en:'dress', ru:'платье', tk:'köýnek', category:'clothes', level:'beginner' },
  { id:179, en:'shoes', ru:'туфли', tk:'aýakgap', category:'clothes', level:'beginner' },
  { id:180, en:'hat', ru:'шапка', tk:'papak', category:'clothes', level:'beginner' },
  { id:181, en:'coat', ru:'пальто', tk:'palto', category:'clothes', level:'beginner' },
  { id:182, en:'jacket', ru:'куртка', tk:'žaket', category:'clothes', level:'beginner' },
  { id:183, en:'scarf', ru:'шарф', tk:'şarf', category:'clothes', level:'beginner' },
  { id:184, en:'gloves', ru:'перчатки', tk:'ellikler', category:'clothes', level:'intermediate' },
  { id:185, en:'socks', ru:'носки', tk:'jorap', category:'clothes', level:'beginner' },
  { id:186, en:'skirt', ru:'юбка', tk:'etek', category:'clothes', level:'beginner' },
  { id:187, en:'belt', ru:'пояс', tk:'guşak', category:'clothes', level:'intermediate' },
  { id:188, en:'tie', ru:'галстук', tk:'galstuk', category:'clothes', level:'intermediate' },

  // PROFESSIONS - Kärler
  { id:189, en:'doctor', ru:'врач', tk:'lukman', category:'professions', level:'beginner' },
  { id:190, en:'engineer', ru:'инженер', tk:'inžener', category:'professions', level:'beginner' },
  { id:191, en:'farmer', ru:'фермер', tk:'daýhan', category:'professions', level:'beginner' },
  { id:192, en:'soldier', ru:'солдат', tk:'esger', category:'professions', level:'beginner' },
  { id:193, en:'driver', ru:'водитель', tk:'sürüji', category:'professions', level:'beginner' },
  { id:194, en:'cook', ru:'повар', tk:'aşpez', category:'professions', level:'beginner' },
  { id:195, en:'police', ru:'полиция', tk:'polisiýa', category:'professions', level:'beginner' },
  { id:196, en:'lawyer', ru:'адвокат', tk:'advokat', category:'professions', level:'intermediate' },
  { id:197, en:'pilot', ru:'лётчик', tk:'uçujy', category:'professions', level:'intermediate' },
  { id:198, en:'scientist', ru:'учёный', tk:'alym', category:'professions', level:'intermediate' },
  { id:199, en:'artist', ru:'художник', tk:'suratkeş', category:'professions', level:'intermediate' },
  { id:200, en:'writer', ru:'писатель', tk:'ýazyjy', category:'professions', level:'intermediate' },
  { id:201, en:'singer', ru:'певец', tk:'aýdymçy', category:'professions', level:'beginner' },
  { id:202, en:'actor', ru:'актёр', tk:'aktýor', category:'professions', level:'intermediate' },
  { id:203, en:'journalist', ru:'журналист', tk:'žurnalist', category:'professions', level:'advanced' },

  // VERBS - Işlikler
  { id:204, en:'run', ru:'бежать', tk:'ylgamak', category:'verbs', level:'beginner' },
  { id:205, en:'walk', ru:'ходить', tk:'ýöremek', category:'verbs', level:'beginner' },
  { id:206, en:'eat', ru:'есть', tk:'iýmek', category:'verbs', level:'beginner' },
  { id:207, en:'drink', ru:'пить', tk:'içmek', category:'verbs', level:'beginner' },
  { id:208, en:'sleep', ru:'спать', tk:'uklama', category:'verbs', level:'beginner' },
  { id:209, en:'work', ru:'работать', tk:'işlemek', category:'verbs', level:'beginner' },
  { id:210, en:'study', ru:'учиться', tk:'okamak', category:'verbs', level:'beginner' },
  { id:211, en:'play', ru:'играть', tk:'oýnamak', category:'verbs', level:'beginner' },
  { id:212, en:'sing', ru:'петь', tk:'aýdym aýtmak', category:'verbs', level:'beginner' },
  { id:213, en:'dance', ru:'танцевать', tk:'tans etmek', category:'verbs', level:'beginner' },
  { id:214, en:'swim', ru:'плавать', tk:'ýüzmek', category:'verbs', level:'beginner' },
  { id:215, en:'read', ru:'читать', tk:'okamak', category:'verbs', level:'beginner' },
  { id:216, en:'write', ru:'писать', tk:'ýazmak', category:'verbs', level:'beginner' },
  { id:217, en:'speak', ru:'говорить', tk:'gürlemek', category:'verbs', level:'beginner' },
  { id:218, en:'listen', ru:'слушать', tk:'diňlemek', category:'verbs', level:'beginner' },
  { id:219, en:'see', ru:'видеть', tk:'görmek', category:'verbs', level:'beginner' },
  { id:220, en:'hear', ru:'слышать', tk:'eşitmek', category:'verbs', level:'beginner' },
  { id:221, en:'know', ru:'знать', tk:'bilmek', category:'verbs', level:'beginner' },
  { id:222, en:'think', ru:'думать', tk:'pikir etmek', category:'verbs', level:'beginner' },
  { id:223, en:'love', ru:'любить', tk:'söýmek', category:'verbs', level:'beginner' },
  { id:224, en:'help', ru:'помогать', tk:'kömek etmek', category:'verbs', level:'beginner' },
  { id:225, en:'buy', ru:'покупать', tk:'satyn almak', category:'verbs', level:'beginner' },
  { id:226, en:'sell', ru:'продавать', tk:'satmak', category:'verbs', level:'beginner' },
  { id:227, en:'come', ru:'приходить', tk:'gelmek', category:'verbs', level:'beginner' },
  { id:228, en:'go', ru:'идти', tk:'gitmek', category:'verbs', level:'beginner' },
  { id:229, en:'open', ru:'открывать', tk:'açmak', category:'verbs', level:'beginner' },
  { id:230, en:'close', ru:'закрывать', tk:'ýapmak', category:'verbs', level:'beginner' },
  { id:231, en:'give', ru:'давать', tk:'bermek', category:'verbs', level:'beginner' },
  { id:232, en:'take', ru:'брать', tk:'almak', category:'verbs', level:'beginner' },
  { id:233, en:'find', ru:'находить', tk:'tapmak', category:'verbs', level:'beginner' },
  { id:234, en:'lose', ru:'терять', tk:'ýitirmek', category:'verbs', level:'intermediate' },
  { id:235, en:'bring', ru:'приносить', tk:'getirmek', category:'verbs', level:'beginner' },
  { id:236, en:'send', ru:'отправлять', tk:'ibermek', category:'verbs', level:'intermediate' },
  { id:237, en:'receive', ru:'получать', tk:'almak', category:'verbs', level:'intermediate' },
  { id:238, en:'make', ru:'делать', tk:'etmek', category:'verbs', level:'beginner' },
  { id:239, en:'build', ru:'строить', tk:'gurmak', category:'verbs', level:'intermediate' },
  { id:240, en:'break', ru:'ломать', tk:'döwmek', category:'verbs', level:'intermediate' },

  // ADJECTIVES - Sypatlar
  { id:241, en:'big', ru:'большой', tk:'uly', category:'adjectives', level:'beginner' },
  { id:242, en:'small', ru:'маленький', tk:'kiçi', category:'adjectives', level:'beginner' },
  { id:243, en:'tall', ru:'высокий', tk:'uzyn', category:'adjectives', level:'beginner' },
  { id:244, en:'short', ru:'короткий', tk:'gysga', category:'adjectives', level:'beginner' },
  { id:245, en:'hot', ru:'горячий', tk:'yssy', category:'adjectives', level:'beginner' },
  { id:246, en:'cold', ru:'холодный', tk:'sowuk', category:'adjectives', level:'beginner' },
  { id:247, en:'fast', ru:'быстрый', tk:'çalt', category:'adjectives', level:'beginner' },
  { id:248, en:'slow', ru:'медленный', tk:'haýal', category:'adjectives', level:'beginner' },
  { id:249, en:'good', ru:'хороший', tk:'gowy', category:'adjectives', level:'beginner' },
  { id:250, en:'bad', ru:'плохой', tk:'erbet', category:'adjectives', level:'beginner' },
  { id:251, en:'beautiful', ru:'красивый', tk:'owadan', category:'adjectives', level:'beginner' },
  { id:252, en:'ugly', ru:'некрасивый', tk:'biabsyr', category:'adjectives', level:'intermediate' },
  { id:253, en:'strong', ru:'сильный', tk:'güýçli', category:'adjectives', level:'beginner' },
  { id:254, en:'weak', ru:'слабый', tk:'ejiz', category:'adjectives', level:'intermediate' },
  { id:255, en:'new', ru:'новый', tk:'täze', category:'adjectives', level:'beginner' },
  { id:256, en:'old', ru:'старый', tk:'köne', category:'adjectives', level:'beginner' },
  { id:257, en:'young', ru:'молодой', tk:'ýaş', category:'adjectives', level:'beginner' },
  { id:258, en:'smart', ru:'умный', tk:'akylly', category:'adjectives', level:'beginner' },
  { id:259, en:'happy', ru:'счастливый', tk:'bagtly', category:'adjectives', level:'beginner' },
  { id:260, en:'sad', ru:'грустный', tk:'gynançly', category:'adjectives', level:'beginner' },
  { id:261, en:'tired', ru:'усталый', tk:'ýadaw', category:'adjectives', level:'intermediate' },
  { id:262, en:'hungry', ru:'голодный', tk:'aç', category:'adjectives', level:'beginner' },
  { id:263, en:'thirsty', ru:'жаждущий', tk:'suwsan', category:'adjectives', level:'intermediate' },
  { id:264, en:'clean', ru:'чистый', tk:'arassa', category:'adjectives', level:'beginner' },
  { id:265, en:'dirty', ru:'грязный', tk:'hapa', category:'adjectives', level:'beginner' },
  { id:266, en:'rich', ru:'богатый', tk:'baý', category:'adjectives', level:'intermediate' },
  { id:267, en:'poor', ru:'бедный', tk:'garyp', category:'adjectives', level:'intermediate' },
  { id:268, en:'easy', ru:'лёгкий', tk:'aňsat', category:'adjectives', level:'beginner' },
  { id:269, en:'difficult', ru:'сложный', tk:'kyn', category:'adjectives', level:'beginner' },
  { id:270, en:'important', ru:'важный', tk:'möhüm', category:'adjectives', level:'intermediate' },

  // TIME - Wagt
  { id:271, en:'morning', ru:'утро', tk:'ir', category:'time', level:'beginner' },
  { id:272, en:'afternoon', ru:'день', tk:'gündiz', category:'time', level:'beginner' },
  { id:273, en:'evening', ru:'вечер', tk:'agşam', category:'time', level:'beginner' },
  { id:274, en:'night', ru:'ночь', tk:'gije', category:'time', level:'beginner' },
  { id:275, en:'today', ru:'сегодня', tk:'bu gün', category:'time', level:'beginner' },
  { id:276, en:'yesterday', ru:'вчера', tk:'düýn', category:'time', level:'beginner' },
  { id:277, en:'tomorrow', ru:'завтра', tk:'ertir', category:'time', level:'beginner' },
  { id:278, en:'week', ru:'неделя', tk:'hepde', category:'time', level:'beginner' },
  { id:279, en:'month', ru:'месяц', tk:'aý', category:'time', level:'beginner' },
  { id:280, en:'year', ru:'год', tk:'ýyl', category:'time', level:'beginner' },
  { id:281, en:'hour', ru:'час', tk:'sagat', category:'time', level:'beginner' },
  { id:282, en:'minute', ru:'минута', tk:'minut', category:'time', level:'beginner' },
  { id:283, en:'second', ru:'секунда', tk:'sekunt', category:'time', level:'beginner' },
  { id:284, en:'Monday', ru:'понедельник', tk:'Duşenbe', category:'time', level:'beginner' },
  { id:285, en:'Tuesday', ru:'вторник', tk:'Sişenbe', category:'time', level:'beginner' },
  { id:286, en:'Wednesday', ru:'среда', tk:'Çarşenbe', category:'time', level:'beginner' },
  { id:287, en:'Thursday', ru:'четверг', tk:'Penşenbe', category:'time', level:'beginner' },
  { id:288, en:'Friday', ru:'пятница', tk:'Anna', category:'time', level:'beginner' },
  { id:289, en:'Saturday', ru:'суббота', tk:'Şenbe', category:'time', level:'beginner' },
  { id:290, en:'Sunday', ru:'воскресенье', tk:'Ýekşenbe', category:'time', level:'beginner' },
  { id:291, en:'January', ru:'январь', tk:'Ýanwar', category:'time', level:'beginner' },
  { id:292, en:'February', ru:'февраль', tk:'Fewral', category:'time', level:'beginner' },
  { id:293, en:'March', ru:'март', tk:'Mart', category:'time', level:'beginner' },
  { id:294, en:'April', ru:'апрель', tk:'Aprel', category:'time', level:'beginner' },
  { id:295, en:'May', ru:'май', tk:'Maý', category:'time', level:'beginner' },
  { id:296, en:'June', ru:'июнь', tk:'Iýun', category:'time', level:'beginner' },
  { id:297, en:'July', ru:'июль', tk:'Iýul', category:'time', level:'beginner' },
  { id:298, en:'August', ru:'август', tk:'Awgust', category:'time', level:'beginner' },
  { id:299, en:'September', ru:'сентябрь', tk:'Sentýabr', category:'time', level:'beginner' },
  { id:300, en:'October', ru:'октябрь', tk:'Oktýabr', category:'time', level:'beginner' },
  { id:301, en:'November', ru:'ноябрь', tk:'Noýabr', category:'time', level:'beginner' },
  { id:302, en:'December', ru:'декабрь', tk:'Dekabr', category:'time', level:'beginner' },

  // HEALTH - Saglyk
  { id:303, en:'health', ru:'здоровье', tk:'saglyk', category:'health', level:'beginner' },
  { id:304, en:'hospital', ru:'больница', tk:'hassahana', category:'health', level:'beginner' },
  { id:305, en:'medicine', ru:'лекарство', tk:'derman', category:'health', level:'beginner' },
  { id:306, en:'pain', ru:'боль', tk:'agyry', category:'health', level:'intermediate' },
  { id:307, en:'fever', ru:'температура', tk:'gyzdyrma', category:'health', level:'intermediate' },
  { id:308, en:'cold', ru:'простуда', tk:'dümewilemek', category:'health', level:'intermediate' },
  { id:309, en:'headache', ru:'головная боль', tk:'baş agyry', category:'health', level:'intermediate' },
  { id:310, en:'surgery', ru:'операция', tk:'operasiýa', category:'health', level:'advanced' },
  { id:311, en:'nurse', ru:'медсестра', tk:'şepagat uýasy', category:'health', level:'intermediate' },
  { id:312, en:'pharmacy', ru:'аптека', tk:'dermanhana', category:'health', level:'intermediate' },

  // SPORTS - Sport
  { id:313, en:'football', ru:'футбол', tk:'futbol', category:'sports', level:'beginner' },
  { id:314, en:'basketball', ru:'баскетбол', tk:'basketbol', category:'sports', level:'beginner' },
  { id:315, en:'tennis', ru:'теннис', tk:'tennis', category:'sports', level:'beginner' },
  { id:316, en:'swimming', ru:'плавание', tk:'ýüzüş', category:'sports', level:'beginner' },
  { id:317, en:'running', ru:'бег', tk:'ylgy', category:'sports', level:'beginner' },
  { id:318, en:'boxing', ru:'бокс', tk:'boks', category:'sports', level:'intermediate' },
  { id:319, en:'wrestling', ru:'борьба', tk:'göreş', category:'sports', level:'intermediate' },
  { id:320, en:'volleyball', ru:'волейбол', tk:'woleýbol', category:'sports', level:'beginner' },
  { id:321, en:'team', ru:'команда', tk:'topar', category:'sports', level:'beginner' },
  { id:322, en:'champion', ru:'чемпион', tk:'çempion', category:'sports', level:'intermediate' },
  { id:323, en:'medal', ru:'медаль', tk:'medal', category:'sports', level:'intermediate' },
  { id:324, en:'goal', ru:'гол', tk:'gol', category:'sports', level:'beginner' },
  { id:325, en:'game', ru:'игра', tk:'oýun', category:'sports', level:'beginner' },

  // TECHNOLOGY - Tehnologiýa
  { id:326, en:'computer', ru:'компьютер', tk:'kompýuter', category:'technology', level:'beginner' },
  { id:327, en:'phone', ru:'телефон', tk:'telefon', category:'technology', level:'beginner' },
  { id:328, en:'internet', ru:'интернет', tk:'internet', category:'technology', level:'beginner' },
  { id:329, en:'television', ru:'телевизор', tk:'telewizor', category:'technology', level:'beginner' },
  { id:330, en:'radio', ru:'радио', tk:'radio', category:'technology', level:'beginner' },
  { id:331, en:'camera', ru:'камера', tk:'kamera', category:'technology', level:'intermediate' },
  { id:332, en:'keyboard', ru:'клавиатура', tk:'klawiatura', category:'technology', level:'intermediate' },
  { id:333, en:'screen', ru:'экран', tk:'ekran', category:'technology', level:'intermediate' },
  { id:334, en:'battery', ru:'батарея', tk:'batareýa', category:'technology', level:'intermediate' },
  { id:335, en:'electricity', ru:'электричество', tk:'elektrik', category:'technology', level:'intermediate' },
  { id:336, en:'robot', ru:'робот', tk:'robot', category:'technology', level:'advanced' },
  { id:337, en:'satellite', ru:'спутник', tk:'emeli hemra', category:'technology', level:'advanced' },
  { id:338, en:'program', ru:'программа', tk:'programma', category:'technology', level:'intermediate' },
  { id:339, en:'password', ru:'пароль', tk:'açar sözi', category:'technology', level:'intermediate' },
  { id:340, en:'website', ru:'сайт', tk:'saýt', category:'technology', level:'intermediate' },

  // PLACES - Ýerler
  { id:341, en:'city', ru:'город', tk:'şäher', category:'places', level:'beginner' },
  { id:342, en:'village', ru:'деревня', tk:'oba', category:'places', level:'beginner' },
  { id:343, en:'country', ru:'страна', tk:'ýurt', category:'places', level:'beginner' },
  { id:344, en:'market', ru:'рынок', tk:'bazar', category:'places', level:'beginner' },
  { id:345, en:'park', ru:'парк', tk:'seýilgäh', category:'places', level:'beginner' },
  { id:346, en:'airport', ru:'аэропорт', tk:'howa menzili', category:'places', level:'intermediate' },
  { id:347, en:'station', ru:'станция', tk:'wokzal', category:'places', level:'intermediate' },
  { id:348, en:'museum', ru:'музей', tk:'muzeý', category:'places', level:'intermediate' },
  { id:349, en:'bank', ru:'банк', tk:'bank', category:'places', level:'intermediate' },
  { id:350, en:'hotel', ru:'гостиница', tk:'myhmanhana', category:'places', level:'intermediate' },
  { id:351, en:'restaurant', ru:'ресторан', tk:'restoran', category:'places', level:'intermediate' },
  { id:352, en:'mosque', ru:'мечеть', tk:'metjit', category:'places', level:'beginner' },
  { id:353, en:'church', ru:'церковь', tk:'buthanа', category:'places', level:'intermediate' },
  { id:354, en:'factory', ru:'завод', tk:'zawod', category:'places', level:'intermediate' },
  { id:355, en:'farm', ru:'ферма', tk:'ferma', category:'places', level:'beginner' },
  { id:356, en:'office', ru:'офис', tk:'ofis', category:'places', level:'intermediate' },
  { id:357, en:'shop', ru:'магазин', tk:'dükkan', category:'places', level:'beginner' },
  { id:358, en:'stadium', ru:'стадион', tk:'stadion', category:'places', level:'intermediate' },
  { id:359, en:'cinema', ru:'кинотеатр', tk:'kinoteatr', category:'places', level:'beginner' },
  { id:360, en:'theater', ru:'театр', tk:'teatr', category:'places', level:'intermediate' },

  // PREPOSITIONS & BASIC - Goşulma we esasy
  { id:361, en:'in', ru:'в', tk:'içinde', category:'basics', level:'beginner' },
  { id:362, en:'on', ru:'на', tk:'üstünde', category:'basics', level:'beginner' },
  { id:363, en:'under', ru:'под', tk:'aşagynda', category:'basics', level:'beginner' },
  { id:364, en:'above', ru:'над', tk:'ýokarda', category:'basics', level:'beginner' },
  { id:365, en:'before', ru:'до', tk:'öňünde', category:'basics', level:'beginner' },
  { id:366, en:'after', ru:'после', tk:'soňra', category:'basics', level:'beginner' },
  { id:367, en:'and', ru:'и', tk:'we', category:'basics', level:'beginner' },
  { id:368, en:'but', ru:'но', tk:'ýöne', category:'basics', level:'beginner' },
  { id:369, en:'or', ru:'или', tk:'ýa-da', category:'basics', level:'beginner' },
  { id:370, en:'because', ru:'потому что', tk:'sebäbi', category:'basics', level:'intermediate' },
  { id:371, en:'if', ru:'если', tk:'eger', category:'basics', level:'intermediate' },
  { id:372, en:'with', ru:'с', tk:'bilen', category:'basics', level:'beginner' },
  { id:373, en:'without', ru:'без', tk:'bolmasa', category:'basics', level:'intermediate' },
  { id:374, en:'yes', ru:'да', tk:'hawa', category:'basics', level:'beginner' },
  { id:375, en:'no', ru:'нет', tk:'ýok', category:'basics', level:'beginner' },
  { id:376, en:'maybe', ru:'может быть', tk:'belki', category:'basics', level:'beginner' },
  { id:377, en:'please', ru:'пожалуйста', tk:'haýyş', category:'basics', level:'beginner' },
  { id:378, en:'thank you', ru:'спасибо', tk:'sag bol', category:'basics', level:'beginner' },
  { id:379, en:'sorry', ru:'извините', tk:'bagyşlaň', category:'basics', level:'beginner' },
  { id:380, en:'hello', ru:'привет', tk:'salam', category:'basics', level:'beginner' },
  { id:381, en:'goodbye', ru:'до свидания', tk:'hoş bol', category:'basics', level:'beginner' },
  { id:382, en:'excuse me', ru:'простите', tk:'bagyşlaň', category:'basics', level:'beginner' },
  { id:383, en:'how are you', ru:'как дела', tk:'ýagdaýlaryňyz nähili', category:'basics', level:'beginner' },
  { id:384, en:'I am fine', ru:'я в порядке', tk:'gowy', category:'basics', level:'beginner' },
  { id:385, en:'what', ru:'что', tk:'näme', category:'basics', level:'beginner' },
  { id:386, en:'where', ru:'где', tk:'nirede', category:'basics', level:'beginner' },
  { id:387, en:'when', ru:'когда', tk:'haçan', category:'basics', level:'beginner' },
  { id:388, en:'why', ru:'почему', tk:'näme üçin', category:'basics', level:'beginner' },
  { id:389, en:'who', ru:'кто', tk:'kim', category:'basics', level:'beginner' },
  { id:390, en:'how', ru:'как', tk:'nähili', category:'basics', level:'beginner' },
  { id:391, en:'how much', ru:'сколько стоит', tk:'näçe', category:'basics', level:'beginner' },
  { id:392, en:'I', ru:'я', tk:'men', category:'basics', level:'beginner' },
  { id:393, en:'you', ru:'ты', tk:'sen', category:'basics', level:'beginner' },
  { id:394, en:'he', ru:'он', tk:'ol', category:'basics', level:'beginner' },
  { id:395, en:'she', ru:'она', tk:'ol', category:'basics', level:'beginner' },
  { id:396, en:'we', ru:'мы', tk:'biz', category:'basics', level:'beginner' },
  { id:397, en:'they', ru:'они', tk:'olar', category:'basics', level:'beginner' },
  { id:398, en:'my', ru:'мой', tk:'meniň', category:'basics', level:'beginner' },
  { id:399, en:'your', ru:'твой', tk:'seniň', category:'basics', level:'beginner' },
  { id:400, en:'his', ru:'его', tk:'onuň', category:'basics', level:'beginner' },

  // EMOTIONS - Duýgular
  { id:401, en:'love', ru:'любовь', tk:'söýgi', category:'emotions', level:'beginner' },
  { id:402, en:'happiness', ru:'счастье', tk:'bagt', category:'emotions', level:'beginner' },
  { id:403, en:'sadness', ru:'грусть', tk:'gynанç', category:'emotions', level:'intermediate' },
  { id:404, en:'anger', ru:'злость', tk:'gahar', category:'emotions', level:'intermediate' },
  { id:405, en:'fear', ru:'страх', tk:'gorky', category:'emotions', level:'intermediate' },
  { id:406, en:'surprise', ru:'удивление', tk:'geňlik', category:'emotions', level:'intermediate' },
  { id:407, en:'hope', ru:'надежда', tk:'umyt', category:'emotions', level:'intermediate' },
  { id:408, en:'dream', ru:'мечта', tk:'düýş', category:'emotions', level:'beginner' },
  { id:409, en:'laugh', ru:'смеяться', tk:'gülmek', category:'emotions', level:'beginner' },
  { id:410, en:'cry', ru:'плакать', tk:'aglamak', category:'emotions', level:'beginner' },

  // SCIENCE - Ylym
  { id:411, en:'science', ru:'наука', tk:'ylym', category:'science', level:'intermediate' },
  { id:412, en:'mathematics', ru:'математика', tk:'matematika', category:'science', level:'beginner' },
  { id:413, en:'physics', ru:'физика', tk:'fizika', category:'science', level:'intermediate' },
  { id:414, en:'chemistry', ru:'химия', tk:'himiýa', category:'science', level:'intermediate' },
  { id:415, en:'biology', ru:'биология', tk:'biologiýa', category:'science', level:'intermediate' },
  { id:416, en:'history', ru:'история', tk:'taryh', category:'science', level:'beginner' },
  { id:417, en:'geography', ru:'география', tk:'geografiýa', category:'science', level:'beginner' },
  { id:418, en:'language', ru:'язык', tk:'dil', category:'science', level:'beginner' },
  { id:419, en:'literature', ru:'литература', tk:'edebiýat', category:'science', level:'intermediate' },
  { id:420, en:'philosophy', ru:'философия', tk:'filosofiýa', category:'science', level:'advanced' },
  { id:421, en:'psychology', ru:'психология', tk:'psihologiýa', category:'science', level:'advanced' },
  { id:422, en:'economics', ru:'экономика', tk:'ykdysadyýet', category:'science', level:'advanced' },
  { id:423, en:'politics', ru:'политика', tk:'syýasat', category:'science', level:'advanced' },
  { id:424, en:'law', ru:'закон', tk:'kanun', category:'science', level:'intermediate' },
  { id:425, en:'art', ru:'искусство', tk:'sungat', category:'science', level:'beginner' },

  // MUSIC - Saz
  { id:426, en:'music', ru:'музыка', tk:'saz', category:'music', level:'beginner' },
  { id:427, en:'song', ru:'песня', tk:'aýdym', category:'music', level:'beginner' },
  { id:428, en:'guitar', ru:'гитара', tk:'gitara', category:'music', level:'beginner' },
  { id:429, en:'piano', ru:'пианино', tk:'piano', category:'music', level:'beginner' },
  { id:430, en:'drum', ru:'барабан', tk:'deprek', category:'music', level:'beginner' },
  { id:431, en:'violin', ru:'скрипка', tk:'skripka', category:'music', level:'intermediate' },
  { id:432, en:'concert', ru:'концерт', tk:'konsert', category:'music', level:'intermediate' },
  { id:433, en:'melody', ru:'мелодия', tk:'heň', category:'music', level:'intermediate' },
  { id:434, en:'rhythm', ru:'ритм', tk:'ritm', category:'music', level:'intermediate' },
  { id:435, en:'singer', ru:'певец', tk:'aýdymçy', category:'music', level:'beginner' },

  // MONEY - Pul
  { id:436, en:'money', ru:'деньги', tk:'pul', category:'money', level:'beginner' },
  { id:437, en:'price', ru:'цена', tk:'baha', category:'money', level:'beginner' },
  { id:438, en:'cheap', ru:'дёшево', tk:'arzan', category:'money', level:'beginner' },
  { id:439, en:'expensive', ru:'дорого', tk:'gymmat', category:'money', level:'beginner' },
  { id:440, en:'pay', ru:'платить', tk:'tölemek', category:'money', level:'intermediate' },
  { id:441, en:'save', ru:'экономить', tk:'tygşytlamak', category:'money', level:'intermediate' },
  { id:442, en:'earn', ru:'зарабатывать', tk:'gazanmak', category:'money', level:'intermediate' },
  { id:443, en:'spend', ru:'тратить', tk:'sarp etmek', category:'money', level:'intermediate' },
  { id:444, en:'invest', ru:'инвестировать', tk:'goýmak', category:'money', level:'advanced' },
  { id:445, en:'tax', ru:'налог', tk:'salgyt', category:'money', level:'advanced' },

  // WEATHER - Howa
  { id:446, en:'weather', ru:'погода', tk:'howa', category:'weather', level:'beginner' },
  { id:447, en:'temperature', ru:'температура', tk:'temperatura', category:'weather', level:'intermediate' },
  { id:448, en:'storm', ru:'буря', tk:'tupan', category:'weather', level:'intermediate' },
  { id:449, en:'thunder', ru:'гром', tk:'güpürdi', category:'weather', level:'intermediate' },
  { id:450, en:'lightning', ru:'молния', tk:'ýyldyrym', category:'weather', level:'intermediate' },
  { id:451, en:'fog', ru:'туман', tk:'duman', category:'weather', level:'intermediate' },
  { id:452, en:'rainbow', ru:'радуга', tk:'älemgoşar', category:'weather', level:'beginner' },
  { id:453, en:'flood', ru:'наводнение', tk:'sil', category:'weather', level:'advanced' },
  { id:454, en:'drought', ru:'засуха', tk:'gurakçylyk', category:'weather', level:'advanced' },
  { id:455, en:'sunny', ru:'солнечный', tk:'güneşli', category:'weather', level:'beginner' },

  // DIRECTIONS - Ugurlar
  { id:456, en:'north', ru:'север', tk:'demirgazyk', category:'directions', level:'beginner' },
  { id:457, en:'south', ru:'юг', tk:'günorta', category:'directions', level:'beginner' },
  { id:458, en:'east', ru:'восток', tk:'gündogar', category:'directions', level:'beginner' },
  { id:459, en:'west', ru:'запад', tk:'günbatar', category:'directions', level:'beginner' },
  { id:460, en:'left', ru:'левый', tk:'çep', category:'directions', level:'beginner' },
  { id:461, en:'right', ru:'правый', tk:'sag', category:'directions', level:'beginner' },
  { id:462, en:'straight', ru:'прямо', tk:'göni', category:'directions', level:'beginner' },
  { id:463, en:'forward', ru:'вперёд', tk:'öňe', category:'directions', level:'beginner' },
  { id:464, en:'back', ru:'назад', tk:'yza', category:'directions', level:'beginner' },
  { id:465, en:'near', ru:'близко', tk:'ýakyn', category:'directions', level:'beginner' },
  { id:466, en:'far', ru:'далеко', tk:'uzak', category:'directions', level:'beginner' },

  // ADVANCED WORDS
  { id:467, en:'achievement', ru:'достижение', tk:'üstünlik', category:'advanced', level:'advanced' },
  { id:468, en:'adventure', ru:'приключение', tk:'başdan geçirme', category:'advanced', level:'advanced' },
  { id:469, en:'agreement', ru:'соглашение', tk:'ylalaşyk', category:'advanced', level:'advanced' },
  { id:470, en:'appearance', ru:'внешность', tk:'görnüş', category:'advanced', level:'advanced' },
  { id:471, en:'argument', ru:'спор', tk:'jedel', category:'advanced', level:'advanced' },
  { id:472, en:'atmosphere', ru:'атмосфера', tk:'atmosfera', category:'advanced', level:'advanced' },
  { id:473, en:'attention', ru:'внимание', tk:'üns', category:'advanced', level:'advanced' },
  { id:474, en:'authority', ru:'власть', tk:'häkimiýet', category:'advanced', level:'advanced' },
  { id:475, en:'balance', ru:'баланс', tk:'deňagramlylyk', category:'advanced', level:'advanced' },
  { id:476, en:'behavior', ru:'поведение', tk:'özüni alyp baryş', category:'advanced', level:'advanced' },
  { id:477, en:'benefit', ru:'выгода', tk:'peýda', category:'advanced', level:'advanced' },
  { id:478, en:'challenge', ru:'вызов', tk:'kynçylyk', category:'advanced', level:'advanced' },
  { id:479, en:'character', ru:'характер', tk:'häsiýet', category:'advanced', level:'advanced' },
  { id:480, en:'communication', ru:'общение', tk:'aragatnaşyk', category:'advanced', level:'advanced' },
  { id:481, en:'community', ru:'сообщество', tk:'jemgyýet', category:'advanced', level:'advanced' },
  { id:482, en:'competition', ru:'конкуренция', tk:'bäsleşik', category:'advanced', level:'advanced' },
  { id:483, en:'confidence', ru:'уверенность', tk:'ynamlylyk', category:'advanced', level:'advanced' },
  { id:484, en:'consequence', ru:'последствие', tk:'netije', category:'advanced', level:'advanced' },
  { id:485, en:'contribution', ru:'вклад', tk:'goşant', category:'advanced', level:'advanced' },
  { id:486, en:'creativity', ru:'творчество', tk:'döredijilik', category:'advanced', level:'advanced' },
  { id:487, en:'culture', ru:'культура', tk:'medeniýet', category:'advanced', level:'advanced' },
  { id:488, en:'decision', ru:'решение', tk:'karar', category:'advanced', level:'advanced' },
  { id:489, en:'democracy', ru:'демократия', tk:'demokratiýa', category:'advanced', level:'advanced' },
  { id:490, en:'development', ru:'развитие', tk:'ösüş', category:'advanced', level:'advanced' },
  { id:491, en:'difference', ru:'разница', tk:'tapawut', category:'advanced', level:'advanced' },
  { id:492, en:'discussion', ru:'дискуссия', tk:'pikir alyşma', category:'advanced', level:'advanced' },
  { id:493, en:'education', ru:'образование', tk:'bilim', category:'advanced', level:'intermediate' },
  { id:494, en:'environment', ru:'окружающая среда', tk:'daşky gurşaw', category:'advanced', level:'advanced' },
  { id:495, en:'experience', ru:'опыт', tk:'tejribe', category:'advanced', level:'advanced' },
  { id:496, en:'explanation', ru:'объяснение', tk:'düşündiriş', category:'advanced', level:'advanced' },
  { id:497, en:'freedom', ru:'свобода', tk:'azatlyk', category:'advanced', level:'advanced' },
  { id:498, en:'generation', ru:'поколение', tk:'nesil', category:'advanced', level:'advanced' },
  { id:499, en:'government', ru:'правительство', tk:'hökümet', category:'advanced', level:'advanced' },
  { id:500, en:'imagination', ru:'воображение', tk:'hyýal', category:'advanced', level:'advanced' },

  // 501-700 continuing...
  { id:501, en:'independence', ru:'независимость', tk:'garaşsyzlyk', category:'advanced', level:'advanced' },
  { id:502, en:'influence', ru:'влияние', tk:'täsir', category:'advanced', level:'advanced' },
  { id:503, en:'information', ru:'информация', tk:'maglumat', category:'advanced', level:'intermediate' },
  { id:504, en:'intelligence', ru:'интеллект', tk:'akyl-paýhas', category:'advanced', level:'advanced' },
  { id:505, en:'invention', ru:'изобретение', tk:'oýlap tapyş', category:'advanced', level:'advanced' },
  { id:506, en:'justice', ru:'справедливость', tk:'adalat', category:'advanced', level:'advanced' },
  { id:507, en:'knowledge', ru:'знание', tk:'bilim', category:'advanced', level:'advanced' },
  { id:508, en:'leadership', ru:'руководство', tk:'ýolbaşçylyk', category:'advanced', level:'advanced' },
  { id:509, en:'memory', ru:'память', tk:'ýat', category:'advanced', level:'intermediate' },
  { id:510, en:'message', ru:'сообщение', tk:'habar', category:'advanced', level:'intermediate' },
  { id:511, en:'opportunity', ru:'возможность', tk:'mümkinçilik', category:'advanced', level:'advanced' },
  { id:512, en:'organization', ru:'организация', tk:'gurama', category:'advanced', level:'advanced' },
  { id:513, en:'patience', ru:'терпение', tk:'sabyr', category:'advanced', level:'intermediate' },
  { id:514, en:'peace', ru:'мир', tk:'parahatçylyk', category:'advanced', level:'intermediate' },
  { id:515, en:'population', ru:'население', tk:'ilat', category:'advanced', level:'advanced' },
  { id:516, en:'power', ru:'сила', tk:'güýç', category:'advanced', level:'intermediate' },
  { id:517, en:'principle', ru:'принцип', tk:'prinsip', category:'advanced', level:'advanced' },
  { id:518, en:'problem', ru:'проблема', tk:'mesele', category:'advanced', level:'intermediate' },
  { id:519, en:'process', ru:'процесс', tk:'proses', category:'advanced', level:'advanced' },
  { id:520, en:'progress', ru:'прогресс', tk:'ösüş', category:'advanced', level:'advanced' },
  { id:521, en:'protection', ru:'защита', tk:'goramak', category:'advanced', level:'advanced' },
  { id:522, en:'quality', ru:'качество', tk:'hil', category:'advanced', level:'advanced' },
  { id:523, en:'question', ru:'вопрос', tk:'sorag', category:'intermediate', level:'beginner' },
  { id:524, en:'answer', ru:'ответ', tk:'jogap', category:'intermediate', level:'beginner' },
  { id:525, en:'reason', ru:'причина', tk:'sebäp', category:'advanced', level:'intermediate' },
  { id:526, en:'relationship', ru:'отношения', tk:'gatnaşyk', category:'advanced', level:'advanced' },
  { id:527, en:'religion', ru:'религия', tk:'din', category:'advanced', level:'advanced' },
  { id:528, en:'research', ru:'исследование', tk:'ylmy iş', category:'advanced', level:'advanced' },
  { id:529, en:'responsibility', ru:'ответственность', tk:'jogapkärçilik', category:'advanced', level:'advanced' },
  { id:530, en:'result', ru:'результат', tk:'netije', category:'advanced', level:'intermediate' },
  { id:531, en:'revolution', ru:'революция', tk:'rewolýusiýa', category:'advanced', level:'advanced' },
  { id:532, en:'risk', ru:'риск', tk:'töwekgelçilik', category:'advanced', level:'advanced' },
  { id:533, en:'rule', ru:'правило', tk:'düzgün', category:'advanced', level:'intermediate' },
  { id:534, en:'safety', ru:'безопасность', tk:'howpsuzlyk', category:'advanced', level:'advanced' },
  { id:535, en:'situation', ru:'ситуация', tk:'ýagdaý', category:'advanced', level:'advanced' },
  { id:536, en:'skill', ru:'навык', tk:'başarnyk', category:'advanced', level:'advanced' },
  { id:537, en:'society', ru:'общество', tk:'jemgyýet', category:'advanced', level:'advanced' },
  { id:538, en:'solution', ru:'решение', tk:'çözgüt', category:'advanced', level:'advanced' },
  { id:539, en:'success', ru:'успех', tk:'üstünlik', category:'advanced', level:'intermediate' },
  { id:540, en:'support', ru:'поддержка', tk:'goldaw', category:'advanced', level:'intermediate' },
  { id:541, en:'system', ru:'система', tk:'ulgam', category:'advanced', level:'advanced' },
  { id:542, en:'technology', ru:'технология', tk:'tehnologiýa', category:'advanced', level:'intermediate' },
  { id:543, en:'tradition', ru:'традиция', tk:'däp-dessur', category:'advanced', level:'advanced' },
  { id:544, en:'trust', ru:'доверие', tk:'ynаnmak', category:'advanced', level:'intermediate' },
  { id:545, en:'truth', ru:'правда', tk:'hakykat', category:'advanced', level:'intermediate' },
  { id:546, en:'understanding', ru:'понимание', tk:'düşünmek', category:'advanced', level:'advanced' },
  { id:547, en:'value', ru:'ценность', tk:'gymmatlyk', category:'advanced', level:'advanced' },
  { id:548, en:'victory', ru:'победа', tk:'ýeňiş', category:'advanced', level:'intermediate' },
  { id:549, en:'vision', ru:'видение', tk:'göz öňüne getirme', category:'advanced', level:'advanced' },
  { id:550, en:'wisdom', ru:'мудрость', tk:'paýhas', category:'advanced', level:'advanced' },

  // MORE COMMON WORDS 551-700
  { id:551, en:'accident', ru:'авария', tk:'hadysa', category:'intermediate', level:'intermediate' },
  { id:552, en:'address', ru:'адрес', tk:'adres', category:'intermediate', level:'intermediate' },
  { id:553, en:'advice', ru:'совет', tk:'maslahat', category:'intermediate', level:'intermediate' },
  { id:554, en:'age', ru:'возраст', tk:'ýaş', category:'basics', level:'beginner' },
  { id:555, en:'alarm', ru:'тревога', tk:'duýduryş', category:'intermediate', level:'intermediate' },
  { id:556, en:'amount', ru:'количество', tk:'mukdar', category:'intermediate', level:'intermediate' },
  { id:557, en:'animal', ru:'животное', tk:'haýwan', category:'basics', level:'beginner' },
  { id:558, en:'announce', ru:'объявлять', tk:'yglan etmek', category:'intermediate', level:'intermediate' },
  { id:559, en:'apartment', ru:'квартира', tk:'öý', category:'intermediate', level:'intermediate' },
  { id:560, en:'apply', ru:'применять', tk:'ulanmak', category:'intermediate', level:'intermediate' },
  { id:561, en:'approach', ru:'подход', tk:'çemeleşme', category:'advanced', level:'advanced' },
  { id:562, en:'approve', ru:'одобрять', tk:'makullam', category:'advanced', level:'advanced' },
  { id:563, en:'area', ru:'область', tk:'meýdan', category:'intermediate', level:'intermediate' },
  { id:564, en:'army', ru:'армия', tk:'goşun', category:'intermediate', level:'intermediate' },
  { id:565, en:'arrest', ru:'арестовать', tk:'tutmak', category:'advanced', level:'advanced' },
  { id:566, en:'article', ru:'статья', tk:'makala', category:'intermediate', level:'intermediate' },
  { id:567, en:'assist', ru:'помогать', tk:'kömek bermek', category:'intermediate', level:'intermediate' },
  { id:568, en:'attach', ru:'прикреплять', tk:'berkitmek', category:'advanced', level:'advanced' },
  { id:569, en:'attempt', ru:'попытка', tk:'synanyşmak', category:'advanced', level:'advanced' },
  { id:570, en:'attract', ru:'привлекать', tk:'özüne çekmek', category:'advanced', level:'advanced' },
  { id:571, en:'avoid', ru:'избегать', tk:'gaçynmak', category:'advanced', level:'advanced' },
  { id:572, en:'award', ru:'награда', tk:'baýrak', category:'intermediate', level:'intermediate' },
  { id:573, en:'basic', ru:'основной', tk:'esasy', category:'basics', level:'beginner' },
  { id:574, en:'born', ru:'рождённый', tk:'doglan', category:'basics', level:'beginner' },
  { id:575, en:'brain', ru:'мозг', tk:'beýni', category:'body', level:'intermediate' },
  { id:576, en:'break', ru:'перерыв', tk:'dynç almak', category:'basics', level:'beginner' },
  { id:577, en:'bridge', ru:'мост', tk:'köpri', category:'places', level:'beginner' },
  { id:578, en:'bright', ru:'яркий', tk:'ýagty', category:'adjectives', level:'intermediate' },
  { id:579, en:'broad', ru:'широкий', tk:'giň', category:'adjectives', level:'intermediate' },
  { id:580, en:'calm', ru:'спокойный', tk:'asuda', category:'adjectives', level:'intermediate' },
  { id:581, en:'canal', ru:'канал', tk:'kanal', category:'places', level:'intermediate' },
  { id:582, en:'capital', ru:'столица', tk:'paýtagt', category:'places', level:'intermediate' },
  { id:583, en:'careful', ru:'осторожный', tk:'seresap', category:'adjectives', level:'intermediate' },
  { id:584, en:'carry', ru:'нести', tk:'götermek', category:'verbs', level:'beginner' },
  { id:585, en:'cause', ru:'причина', tk:'sebäp', category:'advanced', level:'advanced' },
  { id:586, en:'center', ru:'центр', tk:'merkez', category:'places', level:'beginner' },
  { id:587, en:'century', ru:'век', tk:'asyr', category:'time', level:'intermediate' },
  { id:588, en:'certain', ru:'определённый', tk:'belli', category:'adjectives', level:'intermediate' },
  { id:589, en:'change', ru:'менять', tk:'üýtgetmek', category:'verbs', level:'intermediate' },
  { id:590, en:'charge', ru:'заряд', tk:'töleg', category:'intermediate', level:'intermediate' },
  { id:591, en:'check', ru:'проверять', tk:'barlamak', category:'verbs', level:'intermediate' },
  { id:592, en:'choice', ru:'выбор', tk:'saýlaw', category:'advanced', level:'intermediate' },
  { id:593, en:'citizen', ru:'гражданин', tk:'raýat', category:'advanced', level:'advanced' },
  { id:594, en:'clear', ru:'ясный', tk:'aýdyň', category:'adjectives', level:'intermediate' },
  { id:595, en:'clever', ru:'умный', tk:'akylly', category:'adjectives', level:'intermediate' },
  { id:596, en:'collect', ru:'собирать', tk:'ýygnamak', category:'verbs', level:'intermediate' },
  { id:597, en:'comfortable', ru:'удобный', tk:'amatlы', category:'adjectives', level:'intermediate' },
  { id:598, en:'compare', ru:'сравнивать', tk:'deňeşdirmek', category:'verbs', level:'advanced' },
  { id:599, en:'complete', ru:'завершать', tk:'tamamlamak', category:'verbs', level:'intermediate' },
  { id:600, en:'connect', ru:'соединять', tk:'birikdirmek', category:'verbs', level:'intermediate' },

  // 601-700
  { id:601, en:'consider', ru:'считать', tk:'hasaplamak', category:'verbs', level:'advanced' },
  { id:602, en:'contain', ru:'содержать', tk:'saklamak', category:'verbs', level:'advanced' },
  { id:603, en:'control', ru:'контроль', tk:'dolandyrmak', category:'advanced', level:'advanced' },
  { id:604, en:'correct', ru:'правильный', tk:'dogry', category:'adjectives', level:'beginner' },
  { id:605, en:'count', ru:'считать', tk:'sanamak', category:'verbs', level:'beginner' },
  { id:606, en:'courage', ru:'храбрость', tk:'edermenlik', category:'advanced', level:'intermediate' },
  { id:607, en:'cover', ru:'накрывать', tk:'örtmek', category:'verbs', level:'intermediate' },
  { id:608, en:'create', ru:'создавать', tk:'döretmek', category:'verbs', level:'intermediate' },
  { id:609, en:'cross', ru:'пересекать', tk:'geçmek', category:'verbs', level:'intermediate' },
  { id:610, en:'crowd', ru:'толпа', tk:'märeke', category:'intermediate', level:'intermediate' },
  { id:611, en:'current', ru:'текущий', tk:'häzirki', category:'adjectives', level:'advanced' },
  { id:612, en:'damage', ru:'повреждение', tk:'zeper', category:'advanced', level:'advanced' },
  { id:613, en:'danger', ru:'опасность', tk:'howp', category:'intermediate', level:'intermediate' },
  { id:614, en:'dark', ru:'тёмный', tk:'garaňky', category:'adjectives', level:'beginner' },
  { id:615, en:'dead', ru:'мёртвый', tk:'ölen', category:'adjectives', level:'intermediate' },
  { id:616, en:'deal', ru:'сделка', tk:'ylalaşmak', category:'advanced', level:'advanced' },
  { id:617, en:'defeat', ru:'поражение', tk:'ýeňilmek', category:'advanced', level:'advanced' },
  { id:618, en:'defend', ru:'защищать', tk:'goramak', category:'advanced', level:'advanced' },
  { id:619, en:'delay', ru:'задержка', tk:'gijikdirmek', category:'advanced', level:'advanced' },
  { id:620, en:'deliver', ru:'доставлять', tk:'eltip bermek', category:'advanced', level:'advanced' },
  { id:621, en:'demand', ru:'требование', tk:'talap', category:'advanced', level:'advanced' },
  { id:622, en:'describe', ru:'описывать', tk:'beýan etmek', category:'verbs', level:'advanced' },
  { id:623, en:'design', ru:'дизайн', tk:'dizaýn', category:'intermediate', level:'intermediate' },
  { id:624, en:'destroy', ru:'уничтожать', tk:'ýok etmek', category:'verbs', level:'advanced' },
  { id:625, en:'discover', ru:'открывать', tk:'açmak', category:'verbs', level:'intermediate' },
  { id:626, en:'divide', ru:'делить', tk:'bölmek', category:'verbs', level:'intermediate' },
  { id:627, en:'double', ru:'двойной', tk:'goşa', category:'adjectives', level:'intermediate' },
  { id:628, en:'drop', ru:'падать', tk:'düşürmek', category:'verbs', level:'beginner' },
  { id:629, en:'during', ru:'во время', tk:'mahalynda', category:'basics', level:'intermediate' },
  { id:630, en:'duty', ru:'долг', tk:'borç', category:'advanced', level:'advanced' },
  { id:631, en:'effect', ru:'эффект', tk:'täsir', category:'advanced', level:'advanced' },
  { id:632, en:'effort', ru:'усилие', tk:'tagalla', category:'advanced', level:'advanced' },
  { id:633, en:'elect', ru:'выбирать', tk:'saýlamak', category:'advanced', level:'advanced' },
  { id:634, en:'empty', ru:'пустой', tk:'boş', category:'adjectives', level:'beginner' },
  { id:635, en:'end', ru:'конец', tk:'soňy', category:'basics', level:'beginner' },
  { id:636, en:'enemy', ru:'враг', tk:'duşman', category:'intermediate', level:'intermediate' },
  { id:637, en:'energy', ru:'энергия', tk:'energiýa', category:'science', level:'intermediate' },
  { id:638, en:'enjoy', ru:'наслаждаться', tk:'lezzet almak', category:'verbs', level:'intermediate' },
  { id:639, en:'enough', ru:'достаточно', tk:'ýeterli', category:'basics', level:'intermediate' },
  { id:640, en:'enter', ru:'входить', tk:'girmek', category:'verbs', level:'beginner' },
  { id:641, en:'equal', ru:'равный', tk:'deň', category:'adjectives', level:'intermediate' },
  { id:642, en:'escape', ru:'сбегать', tk:'gaçmak', category:'verbs', level:'intermediate' },
  { id:643, en:'event', ru:'событие', tk:'waka', category:'intermediate', level:'intermediate' },
  { id:644, en:'example', ru:'пример', tk:'mysal', category:'basics', level:'beginner' },
  { id:645, en:'excellent', ru:'отличный', tk:'ajaýyp', category:'adjectives', level:'intermediate' },
  { id:646, en:'expect', ru:'ожидать', tk:'garaşmak', category:'verbs', level:'intermediate' },
  { id:647, en:'explain', ru:'объяснять', tk:'düşündirmek', category:'verbs', level:'intermediate' },
  { id:648, en:'express', ru:'выражать', tk:'beýan etmek', category:'verbs', level:'advanced' },
  { id:649, en:'extra', ru:'дополнительный', tk:'goşmaça', category:'adjectives', level:'intermediate' },
  { id:650, en:'face', ru:'лицо', tk:'ýüz', category:'body', level:'beginner' },
  { id:651, en:'fact', ru:'факт', tk:'fakt', category:'intermediate', level:'intermediate' },
  { id:652, en:'fail', ru:'проваливаться', tk:'başa barmamak', category:'verbs', level:'intermediate' },
  { id:653, en:'fair', ru:'справедливый', tk:'adalatly', category:'adjectives', level:'intermediate' },
  { id:654, en:'fall', ru:'падать', tk:'düşmek', category:'verbs', level:'beginner' },
  { id:655, en:'famous', ru:'известный', tk:'meşhur', category:'adjectives', level:'intermediate' },
  { id:656, en:'field', ru:'поле', tk:'meýdan', category:'places', level:'beginner' },
  { id:657, en:'fight', ru:'бороться', tk:'söweşmek', category:'verbs', level:'intermediate' },
  { id:658, en:'fill', ru:'заполнять', tk:'doldurmak', category:'verbs', level:'beginner' },
  { id:659, en:'final', ru:'финальный', tk:'soňky', category:'adjectives', level:'intermediate' },
  { id:660, en:'follow', ru:'следовать', tk:'yzarlamak', category:'verbs', level:'intermediate' },
  { id:661, en:'force', ru:'сила', tk:'güýç', category:'advanced', level:'intermediate' },
  { id:662, en:'foreign', ru:'иностранный', tk:'daşary ýurt', category:'adjectives', level:'intermediate' },
  { id:663, en:'forget', ru:'забывать', tk:'unutmak', category:'verbs', level:'beginner' },
  { id:664, en:'form', ru:'форма', tk:'görnüş', category:'advanced', level:'intermediate' },
  { id:665, en:'fresh', ru:'свежий', tk:'täze', category:'adjectives', level:'beginner' },
  { id:666, en:'friend', ru:'друг', tk:'dost', category:'basics', level:'beginner' },
  { id:667, en:'full', ru:'полный', tk:'doly', category:'adjectives', level:'beginner' },
  { id:668, en:'future', ru:'будущее', tk:'geljek', category:'time', level:'intermediate' },
  { id:669, en:'general', ru:'общий', tk:'umuman', category:'adjectives', level:'advanced' },
  { id:670, en:'gentle', ru:'мягкий', tk:'mylaýym', category:'adjectives', level:'intermediate' },
  { id:671, en:'gift', ru:'подарок', tk:'sowgat', category:'basics', level:'beginner' },
  { id:672, en:'global', ru:'глобальный', tk:'global', category:'advanced', level:'advanced' },
  { id:673, en:'grow', ru:'расти', tk:'ösмек', category:'verbs', level:'beginner' },
  { id:674, en:'guard', ru:'охранник', tk:'garawul', category:'intermediate', level:'intermediate' },
  { id:675, en:'guess', ru:'угадывать', tk:'çak etmek', category:'verbs', level:'intermediate' },
  { id:676, en:'guide', ru:'гид', tk:'gollanma', category:'intermediate', level:'intermediate' },
  { id:677, en:'habit', ru:'привычка', tk:'endik', category:'advanced', level:'advanced' },
  { id:678, en:'handle', ru:'справляться', tk:'dolandyrmak', category:'verbs', level:'advanced' },
  { id:679, en:'happen', ru:'случаться', tk:'bolmak', category:'verbs', level:'intermediate' },
  { id:680, en:'hard', ru:'твёрдый', tk:'gaty', category:'adjectives', level:'beginner' },
  { id:681, en:'heavy', ru:'тяжёлый', tk:'agyr', category:'adjectives', level:'beginner' },
  { id:682, en:'hide', ru:'прятать', tk:'gizlemek', category:'verbs', level:'intermediate' },
  { id:683, en:'high', ru:'высокий', tk:'beýik', category:'adjectives', level:'beginner' },
  { id:684, en:'hold', ru:'держать', tk:'tutmak', category:'verbs', level:'beginner' },
  { id:685, en:'honest', ru:'честный', tk:'dogruçyl', category:'adjectives', level:'intermediate' },
  { id:686, en:'human', ru:'человек', tk:'adam', category:'basics', level:'beginner' },
  { id:687, en:'idea', ru:'идея', tk:'pikir', category:'intermediate', level:'beginner' },
  { id:688, en:'identify', ru:'определять', tk:'anyklamak', category:'verbs', level:'advanced' },
  { id:689, en:'imagine', ru:'представлять', tk:'göz öňüne getirmek', category:'verbs', level:'advanced' },
  { id:690, en:'include', ru:'включать', tk:'goşmak', category:'verbs', level:'advanced' },
  { id:691, en:'increase', ru:'увеличивать', tk:'artdyrmak', category:'verbs', level:'advanced' },
  { id:692, en:'indicate', ru:'указывать', tk:'görkezmek', category:'verbs', level:'advanced' },
  { id:693, en:'individual', ru:'личность', tk:'şahsyýet', category:'advanced', level:'advanced' },
  { id:694, en:'industry', ru:'промышленность', tk:'senagat', category:'advanced', level:'advanced' },
  { id:695, en:'interest', ru:'интерес', tk:'gyzyklanma', category:'intermediate', level:'intermediate' },
  { id:696, en:'introduce', ru:'представлять', tk:'tanyşdyrmak', category:'verbs', level:'intermediate' },
  { id:697, en:'involve', ru:'включать', tk:'goşmak', category:'verbs', level:'advanced' },
  { id:698, en:'join', ru:'присоединяться', tk:'goşulmak', category:'verbs', level:'intermediate' },
  { id:699, en:'judge', ru:'судить', tk:'karar bermek', category:'verbs', level:'advanced' },
  { id:700, en:'keep', ru:'хранить', tk:'saklamak', category:'verbs', level:'beginner' },

  // 701-1000
  { id:701, en:'key', ru:'ключ', tk:'açar', category:'basics', level:'beginner' },
  { id:702, en:'kind', ru:'добрый', tk:'mylaýym', category:'adjectives', level:'beginner' },
  { id:703, en:'land', ru:'земля', tk:'ýer', category:'nature', level:'beginner' },
  { id:704, en:'large', ru:'большой', tk:'uly', category:'adjectives', level:'beginner' },
  { id:705, en:'last', ru:'последний', tk:'soňky', category:'adjectives', level:'beginner' },
  { id:706, en:'late', ru:'поздно', tk:'giç', category:'time', level:'beginner' },
  { id:707, en:'laugh', ru:'смеяться', tk:'gülmek', category:'verbs', level:'beginner' },
  { id:708, en:'lead', ru:'вести', tk:'ýolbaşçylyk etmek', category:'verbs', level:'intermediate' },
  { id:709, en:'learn', ru:'учиться', tk:'öwrenmek', category:'verbs', level:'beginner' },
  { id:710, en:'leave', ru:'покидать', tk:'gitmek', category:'verbs', level:'beginner' },
  { id:711, en:'legal', ru:'законный', tk:'kanunly', category:'advanced', level:'advanced' },
  { id:712, en:'let', ru:'позволять', tk:'rugsat bermek', category:'verbs', level:'beginner' },
  { id:713, en:'level', ru:'уровень', tk:'derejê', category:'intermediate', level:'intermediate' },
  { id:714, en:'life', ru:'жизнь', tk:'ömür', category:'basics', level:'beginner' },
  { id:715, en:'light', ru:'свет', tk:'ýagtylyk', category:'nature', level:'beginner' },
  { id:716, en:'like', ru:'нравиться', tk:'halama', category:'verbs', level:'beginner' },
  { id:717, en:'limit', ru:'предел', tk:'çäk', category:'advanced', level:'advanced' },
  { id:718, en:'line', ru:'линия', tk:'çyzyk', category:'basics', level:'beginner' },
  { id:719, en:'link', ru:'связь', tk:'baglanyşyk', category:'advanced', level:'intermediate' },
  { id:720, en:'list', ru:'список', tk:'sanaw', category:'basics', level:'beginner' },
  { id:721, en:'live', ru:'жить', tk:'ýaşamak', category:'verbs', level:'beginner' },
  { id:722, en:'local', ru:'местный', tk:'ýerli', category:'adjectives', level:'intermediate' },
  { id:723, en:'long', ru:'длинный', tk:'uzyn', category:'adjectives', level:'beginner' },
  { id:724, en:'look', ru:'смотреть', tk:'seretmek', category:'verbs', level:'beginner' },
  { id:725, en:'low', ru:'низкий', tk:'pes', category:'adjectives', level:'beginner' },
  { id:726, en:'main', ru:'главный', tk:'esasy', category:'adjectives', level:'intermediate' },
  { id:727, en:'manage', ru:'управлять', tk:'dolandyrmak', category:'verbs', level:'advanced' },
  { id:728, en:'manner', ru:'манера', tk:'edep', category:'advanced', level:'advanced' },
  { id:729, en:'mark', ru:'отметка', tk:'bellik', category:'intermediate', level:'intermediate' },
  { id:730, en:'match', ru:'совпадение', tk:'oýun', category:'intermediate', level:'intermediate' },
  { id:731, en:'matter', ru:'важно', tk:'möhüm', category:'basics', level:'intermediate' },
  { id:732, en:'mean', ru:'означать', tk:'diýmek', category:'verbs', level:'intermediate' },
  { id:733, en:'measure', ru:'измерять', tk:'ölçemek', category:'verbs', level:'intermediate' },
  { id:734, en:'meet', ru:'встречать', tk:'duşmak', category:'verbs', level:'beginner' },
  { id:735, en:'mention', ru:'упоминать', tk:'agzamak', category:'verbs', level:'advanced' },
  { id:736, en:'method', ru:'метод', tk:'usul', category:'advanced', level:'advanced' },
  { id:737, en:'mind', ru:'разум', tk:'akyl', category:'advanced', level:'intermediate' },
  { id:738, en:'miss', ru:'скучать', tk:'küýsemek', category:'verbs', level:'intermediate' },
  { id:739, en:'model', ru:'модель', tk:'nusga', category:'intermediate', level:'intermediate' },
  { id:740, en:'modern', ru:'современный', tk:'häzirki zaman', category:'adjectives', level:'intermediate' },
  { id:741, en:'moment', ru:'момент', tk:'pursat', category:'time', level:'intermediate' },
  { id:742, en:'move', ru:'двигаться', tk:'hereket etmek', category:'verbs', level:'beginner' },
  { id:743, en:'multiply', ru:'умножать', tk:'köpeltmek', category:'verbs', level:'intermediate' },
  { id:744, en:'national', ru:'национальный', tk:'milli', category:'adjectives', level:'intermediate' },
  { id:745, en:'natural', ru:'естественный', tk:'tebigy', category:'adjectives', level:'intermediate' },
  { id:746, en:'necessary', ru:'необходимый', tk:'zerur', category:'adjectives', level:'intermediate' },
  { id:747, en:'need', ru:'нуждаться', tk:'gerek', category:'verbs', level:'beginner' },
  { id:748, en:'normal', ru:'нормальный', tk:'adaty', category:'adjectives', level:'intermediate' },
  { id:749, en:'note', ru:'заметка', tk:'bellik', category:'basics', level:'intermediate' },
  { id:750, en:'notice', ru:'замечать', tk:'duýmak', category:'verbs', level:'intermediate' },
  { id:751, en:'object', ru:'объект', tk:'zat', category:'basics', level:'intermediate' },
  { id:752, en:'observe', ru:'наблюдать', tk:'synlamak', category:'verbs', level:'advanced' },
  { id:753, en:'obtain', ru:'получать', tk:'almak', category:'verbs', level:'advanced' },
  { id:754, en:'offer', ru:'предложить', tk:'teklip etmek', category:'verbs', level:'intermediate' },
  { id:755, en:'official', ru:'официальный', tk:'resmi', category:'adjectives', level:'advanced' },
  { id:756, en:'often', ru:'часто', tk:'köplenç', category:'basics', level:'beginner' },
  { id:757, en:'operate', ru:'работать', tk:'işletmek', category:'verbs', level:'advanced' },
  { id:758, en:'opinion', ru:'мнение', tk:'pikir', category:'intermediate', level:'intermediate' },
  { id:759, en:'order', ru:'заказ', tk:'buýurmak', category:'intermediate', level:'intermediate' },
  { id:760, en:'original', ru:'оригинальный', tk:'asyl', category:'adjectives', level:'intermediate' },
  { id:761, en:'overcome', ru:'преодолевать', tk:'ýeňip geçmek', category:'verbs', level:'advanced' },
  { id:762, en:'own', ru:'собственный', tk:'öz', category:'adjectives', level:'beginner' },
  { id:763, en:'particular', ru:'особый', tk:'aýratyn', category:'adjectives', level:'advanced' },
  { id:764, en:'pass', ru:'сдавать', tk:'geçmek', category:'verbs', level:'beginner' },
  { id:765, en:'past', ru:'прошлое', tk:'geçmiş', category:'time', level:'intermediate' },
  { id:766, en:'perform', ru:'выполнять', tk:'ýerine ýetirmek', category:'verbs', level:'advanced' },
  { id:767, en:'period', ru:'период', tk:'döwür', category:'time', level:'intermediate' },
  { id:768, en:'permit', ru:'разрешать', tk:'rugsat bermek', category:'verbs', level:'advanced' },
  { id:769, en:'person', ru:'человек', tk:'adam', category:'basics', level:'beginner' },
  { id:770, en:'pick', ru:'брать', tk:'almak', category:'verbs', level:'beginner' },
  { id:771, en:'place', ru:'место', tk:'ýer', category:'basics', level:'beginner' },
  { id:772, en:'plan', ru:'план', tk:'meýilnama', category:'intermediate', level:'intermediate' },
  { id:773, en:'plant', ru:'растение', tk:'ösümlik', category:'nature', level:'beginner' },
  { id:774, en:'point', ru:'точка', tk:'nokat', category:'basics', level:'beginner' },
  { id:775, en:'possible', ru:'возможный', tk:'mümkin', category:'adjectives', level:'intermediate' },
  { id:776, en:'prepare', ru:'готовить', tk:'taýýarlamak', category:'verbs', level:'intermediate' },
  { id:777, en:'present', ru:'настоящее', tk:'häzirki', category:'time', level:'intermediate' },
  { id:778, en:'prevent', ru:'предотвращать', tk:'öňüni almak', category:'verbs', level:'advanced' },
  { id:779, en:'produce', ru:'производить', tk:'öndürmek', category:'verbs', level:'advanced' },
  { id:780, en:'prove', ru:'доказывать', tk:'subut etmek', category:'verbs', level:'advanced' },
  { id:781, en:'provide', ru:'обеспечивать', tk:'üpjün etmek', category:'verbs', level:'advanced' },
  { id:782, en:'public', ru:'общественный', tk:'jemgyýetçilik', category:'adjectives', level:'intermediate' },
  { id:783, en:'pull', ru:'тянуть', tk:'çekmek', category:'verbs', level:'beginner' },
  { id:784, en:'push', ru:'толкать', tk:'itmek', category:'verbs', level:'beginner' },
  { id:785, en:'put', ru:'класть', tk:'goýmak', category:'verbs', level:'beginner' },
  { id:786, en:'reach', ru:'достигать', tk:'ýetmek', category:'verbs', level:'intermediate' },
  { id:787, en:'real', ru:'настоящий', tk:'hakyky', category:'adjectives', level:'intermediate' },
  { id:788, en:'recognize', ru:'узнавать', tk:'tanамak', category:'verbs', level:'advanced' },
  { id:789, en:'reduce', ru:'уменьшать', tk:'azaltmak', category:'verbs', level:'advanced' },
  { id:790, en:'refer', ru:'ссылаться', tk:'ýüz tutmak', category:'verbs', level:'advanced' },
  { id:791, en:'reflect', ru:'отражать', tk:'görkezm', category:'verbs', level:'advanced' },
  { id:792, en:'refuse', ru:'отказывать', tk:'ret etmek', category:'verbs', level:'advanced' },
  { id:793, en:'relate', ru:'относить', tk:'baglanyşdyrmak', category:'verbs', level:'advanced' },
  { id:794, en:'remain', ru:'оставаться', tk:'galmak', category:'verbs', level:'intermediate' },
  { id:795, en:'remember', ru:'помнить', tk:'ýatlamak', category:'verbs', level:'beginner' },
  { id:796, en:'remove', ru:'убирать', tk:'aýyrmak', category:'verbs', level:'intermediate' },
  { id:797, en:'repeat', ru:'повторять', tk:'gaýtalamak', category:'verbs', level:'intermediate' },
  { id:798, en:'replace', ru:'заменять', tk:'çalşyrmak', category:'verbs', level:'advanced' },
  { id:799, en:'report', ru:'отчёт', tk:'hasabat', category:'intermediate', level:'intermediate' },
  { id:800, en:'require', ru:'требовать', tk:'talap etmek', category:'verbs', level:'advanced' },
  { id:801, en:'respect', ru:'уважение', tk:'hormat', category:'intermediate', level:'intermediate' },
  { id:802, en:'return', ru:'возвращаться', tk:'gaýtmak', category:'verbs', level:'beginner' },
  { id:803, en:'review', ru:'обзор', tk:'syn', category:'intermediate', level:'intermediate' },
  { id:804, en:'rise', ru:'подниматься', tk:'galmak', category:'verbs', level:'intermediate' },
  { id:805, en:'road', ru:'дорога', tk:'ýol', category:'places', level:'beginner' },
  { id:806, en:'role', ru:'роль', tk:'rol', category:'advanced', level:'advanced' },
  { id:807, en:'round', ru:'круглый', tk:'togalak', category:'adjectives', level:'beginner' },
  { id:808, en:'safe', ru:'безопасный', tk:'howpsuz', category:'adjectives', level:'intermediate' },
  { id:809, en:'same', ru:'одинаковый', tk:'birmeňzeş', category:'adjectives', level:'beginner' },
  { id:810, en:'scale', ru:'масштаб', tk:'gerim', category:'advanced', level:'advanced' },
  { id:811, en:'serve', ru:'служить', tk:'hyzmat etmek', category:'verbs', level:'advanced' },
  { id:812, en:'share', ru:'делиться', tk:'paýlaşmak', category:'verbs', level:'intermediate' },
  { id:813, en:'show', ru:'показывать', tk:'görkezmek', category:'verbs', level:'beginner' },
  { id:814, en:'simple', ru:'простой', tk:'ýönekeý', category:'adjectives', level:'beginner' },
  { id:815, en:'since', ru:'с тех пор', tk:'şondan bäri', category:'basics', level:'intermediate' },
  { id:816, en:'single', ru:'один', tk:'ýeke', category:'adjectives', level:'beginner' },
  { id:817, en:'size', ru:'размер', tk:'ölçeg', category:'basics', level:'beginner' },
  { id:818, en:'sort', ru:'вид', tk:'görnüş', category:'basics', level:'intermediate' },
  { id:819, en:'sound', ru:'звук', tk:'ses', category:'basics', level:'beginner' },
  { id:820, en:'space', ru:'космос', tk:'kosmos', category:'science', level:'intermediate' },
  { id:821, en:'special', ru:'особый', tk:'aýratyn', category:'adjectives', level:'intermediate' },
  { id:822, en:'speed', ru:'скорость', tk:'tizlik', category:'basics', level:'intermediate' },
  { id:823, en:'spread', ru:'распространяться', tk:'ýaýramak', category:'verbs', level:'advanced' },
  { id:824, en:'stand', ru:'стоять', tk:'durmak', category:'verbs', level:'beginner' },
  { id:825, en:'start', ru:'начинать', tk:'başlamak', category:'verbs', level:'beginner' },
  { id:826, en:'stay', ru:'оставаться', tk:'galmak', category:'verbs', level:'beginner' },
  { id:827, en:'step', ru:'шаг', tk:'ädim', category:'basics', level:'beginner' },
  { id:828, en:'still', ru:'всё ещё', tk:'heniz', category:'basics', level:'intermediate' },
  { id:829, en:'stop', ru:'останавливаться', tk:'durmak', category:'verbs', level:'beginner' },
  { id:830, en:'store', ru:'магазин', tk:'dükkan', category:'places', level:'beginner' },
  { id:831, en:'story', ru:'история', tk:'hekaýa', category:'intermediate', level:'beginner' },
  { id:832, en:'strange', ru:'странный', tk:'geň', category:'adjectives', level:'intermediate' },
  { id:833, en:'street', ru:'улица', tk:'köçe', category:'places', level:'beginner' },
  { id:834, en:'struggle', ru:'бороться', tk:'göreşmek', category:'verbs', level:'advanced' },
  { id:835, en:'subject', ru:'предмет', tk:'mowzuk', category:'school', level:'intermediate' },
  { id:836, en:'sure', ru:'уверен', tk:'ynam', category:'adjectives', level:'beginner' },
  { id:837, en:'surround', ru:'окружать', tk:'gurşap almak', category:'verbs', level:'advanced' },
  { id:838, en:'table', ru:'таблица', tk:'tablisa', category:'basics', level:'intermediate' },
  { id:839, en:'talk', ru:'говорить', tk:'gürlemek', category:'verbs', level:'beginner' },
  { id:840, en:'teach', ru:'учить', tk:'öwretmek', category:'verbs', level:'beginner' },
  { id:841, en:'tell', ru:'рассказывать', tk:'aýtmak', category:'verbs', level:'beginner' },
  { id:842, en:'test', ru:'тест', tk:'test', category:'school', level:'beginner' },
  { id:843, en:'together', ru:'вместе', tk:'bile', category:'basics', level:'beginner' },
  { id:844, en:'total', ru:'итого', tk:'jemi', category:'basics', level:'intermediate' },
  { id:845, en:'touch', ru:'касаться', tk:'degmek', category:'verbs', level:'beginner' },
  { id:846, en:'trade', ru:'торговля', tk:'söwda', category:'advanced', level:'advanced' },
  { id:847, en:'train', ru:'тренировать', tk:'türgenleşmek', category:'verbs', level:'intermediate' },
  { id:848, en:'travel', ru:'путешествовать', tk:'syýahat etmek', category:'verbs', level:'intermediate' },
  { id:849, en:'treat', ru:'угощать', tk:'bejermek', category:'verbs', level:'intermediate' },
  { id:850, en:'try', ru:'пробовать', tk:'synanyşmak', category:'verbs', level:'beginner' },
  { id:851, en:'turn', ru:'повернуть', tk:'öwürmek', category:'verbs', level:'beginner' },
  { id:852, en:'type', ru:'тип', tk:'görnüş', category:'basics', level:'intermediate' },
  { id:853, en:'understand', ru:'понимать', tk:'düşünmek', category:'verbs', level:'beginner' },
  { id:854, en:'unite', ru:'объединять', tk:'birleşdirmek', category:'verbs', level:'advanced' },
  { id:855, en:'until', ru:'до', tk:'çenli', category:'basics', level:'intermediate' },
  { id:856, en:'use', ru:'использовать', tk:'ulanmak', category:'verbs', level:'beginner' },
  { id:857, en:'usually', ru:'обычно', tk:'köplenç', category:'basics', level:'intermediate' },
  { id:858, en:'various', ru:'различный', tk:'dürli', category:'adjectives', level:'intermediate' },
  { id:859, en:'view', ru:'вид', tk:'görnüş', category:'basics', level:'intermediate' },
  { id:860, en:'visit', ru:'посещать', tk:'barmak', category:'verbs', level:'beginner' },
  { id:861, en:'voice', ru:'голос', tk:'ses', category:'body', level:'intermediate' },
  { id:862, en:'vote', ru:'голосовать', tk:'ses bermek', category:'advanced', level:'advanced' },
  { id:863, en:'wait', ru:'ждать', tk:'garaşmak', category:'verbs', level:'beginner' },
  { id:864, en:'want', ru:'хотеть', tk:'islemek', category:'verbs', level:'beginner' },
  { id:865, en:'warm', ru:'тёплый', tk:'ýyly', category:'adjectives', level:'beginner' },
  { id:866, en:'watch', ru:'наблюдать', tk:'synlamak', category:'verbs', level:'beginner' },
  { id:867, en:'whole', ru:'целый', tk:'bütin', category:'adjectives', level:'intermediate' },
  { id:868, en:'wide', ru:'широкий', tk:'giň', category:'adjectives', level:'intermediate' },
  { id:869, en:'win', ru:'побеждать', tk:'ýeňmek', category:'verbs', level:'beginner' },
  { id:870, en:'wonder', ru:'удивляться', tk:'haýran galmak', category:'verbs', level:'intermediate' },
  { id:871, en:'word', ru:'слово', tk:'söz', category:'basics', level:'beginner' },
  { id:872, en:'world', ru:'мир', tk:'dünýä', category:'basics', level:'beginner' },
  { id:873, en:'worry', ru:'беспокоиться', tk:'alada etmek', category:'verbs', level:'intermediate' },
  { id:874, en:'worth', ru:'стоить', tk:'baha', category:'advanced', level:'advanced' },
  { id:875, en:'wrong', ru:'неправильный', tk:'nädogry', category:'adjectives', level:'beginner' },
  { id:876, en:'yard', ru:'двор', tk:'howly', category:'house', level:'beginner' },
  { id:877, en:'yet', ru:'ещё', tk:'heniz', category:'basics', level:'intermediate' },
  { id:878, en:'zero', ru:'ноль', tk:'nol', category:'numbers', level:'beginner' },
  { id:879, en:'zone', ru:'зона', tk:'zona', category:'intermediate', level:'intermediate' },
  { id:880, en:'ability', ru:'способность', tk:'başarnyk', category:'advanced', level:'advanced' },
  { id:881, en:'abroad', ru:'за рубежом', tk:'daşary ýurtda', category:'places', level:'intermediate' },
  { id:882, en:'absolutely', ru:'абсолютно', tk:'düýbünden', category:'basics', level:'advanced' },
  { id:883, en:'accept', ru:'принимать', tk:'kabul etmek', category:'verbs', level:'intermediate' },
  { id:884, en:'access', ru:'доступ', tk:'giriş', category:'technology', level:'intermediate' },
  { id:885, en:'according', ru:'согласно', tk:'görä', category:'basics', level:'advanced' },
  { id:886, en:'accurate', ru:'точный', tk:'takyk', category:'adjectives', level:'advanced' },
  { id:887, en:'act', ru:'действовать', tk:'hereket etmek', category:'verbs', level:'intermediate' },
  { id:888, en:'action', ru:'действие', tk:'hereketi', category:'intermediate', level:'intermediate' },
  { id:889, en:'active', ru:'активный', tk:'işjeň', category:'adjectives', level:'intermediate' },
  { id:890, en:'actual', ru:'фактический', tk:'hakyky', category:'adjectives', level:'advanced' },
  { id:891, en:'adapt', ru:'адаптировать', tk:'uýgunlaşmak', category:'verbs', level:'advanced' },
  { id:892, en:'add', ru:'добавлять', tk:'goşmak', category:'verbs', level:'beginner' },
  { id:893, en:'advance', ru:'продвигаться', tk:'öňe gitmek', category:'verbs', level:'advanced' },
  { id:894, en:'affect', ru:'влиять', tk:'täsir etmek', category:'verbs', level:'advanced' },
  { id:895, en:'afford', ru:'позволить', tk:'mümkinçiligi bolmak', category:'verbs', level:'advanced' },
  { id:896, en:'afraid', ru:'бояться', tk:'gorkмak', category:'adjectives', level:'beginner' },
  { id:897, en:'again', ru:'снова', tk:'ýene', category:'basics', level:'beginner' },
  { id:898, en:'against', ru:'против', tk:'garşy', category:'basics', level:'intermediate' },
  { id:899, en:'agent', ru:'агент', tk:'wekil', category:'advanced', level:'advanced' },
  { id:900, en:'ahead', ru:'впереди', tk:'öňde', category:'directions', level:'intermediate' },
  { id:901, en:'allow', ru:'разрешать', tk:'rugsat etmek', category:'verbs', level:'intermediate' },
  { id:902, en:'almost', ru:'почти', tk:'diýen ýaly', category:'basics', level:'intermediate' },
  { id:903, en:'already', ru:'уже', tk:'eýýäm', category:'basics', level:'beginner' },
  { id:904, en:'also', ru:'также', tk:'hem', category:'basics', level:'beginner' },
  { id:905, en:'always', ru:'всегда', tk:'hemişe', category:'basics', level:'beginner' },
  { id:906, en:'among', ru:'среди', tk:'arasynda', category:'basics', level:'intermediate' },
  { id:907, en:'apart', ru:'отдельно', tk:'aýry', category:'basics', level:'intermediate' },
  { id:908, en:'around', ru:'вокруг', tk:'töwereg', category:'basics', level:'beginner' },
  { id:909, en:'arrive', ru:'приезжать', tk:'gelmek', category:'verbs', level:'beginner' },
  { id:910, en:'ask', ru:'спрашивать', tk:'soramak', category:'verbs', level:'beginner' },
  { id:911, en:'assume', ru:'предполагать', tk:'çak etmek', category:'verbs', level:'advanced' },
  { id:912, en:'award', ru:'награда', tk:'baýrak', category:'intermediate', level:'intermediate' },
  { id:913, en:'aware', ru:'осведомлённый', tk:'habarly', category:'adjectives', level:'advanced' },
  { id:914, en:'begin', ru:'начинать', tk:'başlamak', category:'verbs', level:'beginner' },
  { id:915, en:'believe', ru:'верить', tk:'ynanmak', category:'verbs', level:'beginner' },
  { id:916, en:'below', ru:'ниже', tk:'aşakda', category:'basics', level:'beginner' },
  { id:917, en:'beside', ru:'рядом', tk:'ýanynda', category:'basics', level:'beginner' },
  { id:918, en:'between', ru:'между', tk:'arasynda', category:'basics', level:'beginner' },
  { id:919, en:'beyond', ru:'за пределами', tk:'aňyrsynda', category:'basics', level:'advanced' },
  { id:920, en:'both', ru:'оба', tk:'ikisi hem', category:'basics', level:'beginner' },
  { id:921, en:'busy', ru:'занятый', tk:'hysyrdanly', category:'adjectives', level:'beginner' },
  { id:922, en:'call', ru:'звонить', tk:'jaň etmek', category:'verbs', level:'beginner' },
  { id:923, en:'care', ru:'заботиться', tk:'alada etmek', category:'verbs', level:'beginner' },
  { id:924, en:'catch', ru:'ловить', tk:'tutmak', category:'verbs', level:'beginner' },
  { id:925, en:'cause', ru:'вызывать', tk:'döretmek', category:'verbs', level:'intermediate' },
  { id:926, en:'chat', ru:'болтать', tk:'gürrüň etmek', category:'verbs', level:'beginner' },
  { id:927, en:'choose', ru:'выбирать', tk:'saýlamak', category:'verbs', level:'beginner' },
  { id:928, en:'claim', ru:'утверждать', tk:'talap etmek', category:'verbs', level:'advanced' },
  { id:929, en:'common', ru:'обычный', tk:'adaty', category:'adjectives', level:'intermediate' },
  { id:930, en:'concern', ru:'беспокойство', tk:'alada', category:'advanced', level:'advanced' },
  { id:931, en:'condition', ru:'условие', tk:'şert', category:'advanced', level:'advanced' },
  { id:932, en:'confirm', ru:'подтверждать', tk:'tassyklamak', category:'verbs', level:'advanced' },
  { id:933, en:'continue', ru:'продолжать', tk:'dowam etmek', category:'verbs', level:'intermediate' },
  { id:934, en:'copy', ru:'копировать', tk:'göçürmek', category:'verbs', level:'intermediate' },
  { id:935, en:'cut', ru:'резать', tk:'kesmek', category:'verbs', level:'beginner' },
  { id:936, en:'decide', ru:'решать', tk:'karar bermek', category:'verbs', level:'intermediate' },
  { id:937, en:'deep', ru:'глубокий', tk:'çuň', category:'adjectives', level:'intermediate' },
  { id:938, en:'depend', ru:'зависеть', tk:'bagly bolmak', category:'verbs', level:'advanced' },
  { id:939, en:'die', ru:'умирать', tk:'ölmek', category:'verbs', level:'intermediate' },
  { id:940, en:'direct', ru:'прямой', tk:'göni', category:'adjectives', level:'intermediate' },
  { id:941, en:'draw', ru:'рисовать', tk:'çekmek', category:'verbs', level:'beginner' },
  { id:942, en:'dream', ru:'мечтать', tk:'arzuw etmek', category:'verbs', level:'beginner' },
  { id:943, en:'drive', ru:'водить', tk:'sürm', category:'verbs', level:'beginner' },
  { id:944, en:'earn', ru:'зарабатывать', tk:'gazanmak', category:'verbs', level:'intermediate' },
  { id:945, en:'else', ru:'ещё', tk:'başga', category:'basics', level:'beginner' },
  { id:946, en:'even', ru:'даже', tk:'hatda', category:'basics', level:'intermediate' },
  { id:947, en:'ever', ru:'когда-либо', tk:'haçanam', category:'basics', level:'intermediate' },
  { id:948, en:'every', ru:'каждый', tk:'her', category:'basics', level:'beginner' },
  { id:949, en:'exact', ru:'точный', tk:'takyk', category:'adjectives', level:'intermediate' },
  { id:950, en:'except', ru:'кроме', tk:'başga', category:'basics', level:'intermediate' },
  { id:951, en:'exist', ru:'существовать', tk:'bar bolmak', category:'verbs', level:'advanced' },
  { id:952, en:'expand', ru:'расширять', tk:'giňeltmek', category:'verbs', level:'advanced' },
  { id:953, en:'expect', ru:'ожидать', tk:'garaşmak', category:'verbs', level:'intermediate' },
  { id:954, en:'extend', ru:'расширять', tk:'uzaltmak', category:'verbs', level:'advanced' },
  { id:955, en:'feature', ru:'особенность', tk:'aýratynlyk', category:'advanced', level:'advanced' },
  { id:956, en:'feel', ru:'чувствовать', tk:'duýmak', category:'verbs', level:'beginner' },
  { id:957, en:'few', ru:'немного', tk:'birnäçe', category:'basics', level:'beginner' },
  { id:958, en:'fix', ru:'чинить', tk:'düzetmek', category:'verbs', level:'intermediate' },
  { id:959, en:'focus', ru:'сосредоточиться', tk:'üns bermek', category:'verbs', level:'intermediate' },
  { id:960, en:'form', ru:'заполнять', tk:'doldurmak', category:'verbs', level:'intermediate' },
  { id:961, en:'free', ru:'свободный', tk:'azat', category:'adjectives', level:'beginner' },
  { id:962, en:'front', ru:'перед', tk:'öň', category:'directions', level:'beginner' },
  { id:963, en:'gain', ru:'получать', tk:'gazanmak', category:'verbs', level:'intermediate' },
  { id:964, en:'glad', ru:'рад', tk:'şat', category:'adjectives', level:'beginner' },
  { id:965, en:'great', ru:'великий', tk:'beýik', category:'adjectives', level:'beginner' },
  { id:966, en:'habit', ru:'привычка', tk:'endik', category:'advanced', level:'advanced' },
  { id:967, en:'half', ru:'половина', tk:'ýary', category:'numbers', level:'beginner' },
  { id:968, en:'hate', ru:'ненавидеть', tk:'ýigrenm', category:'verbs', level:'intermediate' },
  { id:969, en:'have', ru:'иметь', tk:'bolmak', category:'verbs', level:'beginner' },
  { id:970, en:'help', ru:'помочь', tk:'kömek etmek', category:'verbs', level:'beginner' },
  { id:971, en:'home', ru:'дом', tk:'öý', category:'house', level:'beginner' },
  { id:972, en:'hope', ru:'надеяться', tk:'umyt etmek', category:'verbs', level:'beginner' },
  { id:973, en:'hurt', ru:'болеть', tk:'agyrmak', category:'verbs', level:'intermediate' },
  { id:974, en:'inside', ru:'внутри', tk:'içinde', category:'basics', level:'beginner' },
  { id:975, en:'instead', ru:'вместо', tk:'deregine', category:'basics', level:'intermediate' },
  { id:976, en:'keep', ru:'хранить', tk:'saklamak', category:'verbs', level:'beginner' },
  { id:977, en:'lack', ru:'нехватка', tk:'ýetmezçilik', category:'advanced', level:'advanced' },
  { id:978, en:'laugh', ru:'смеяться', tk:'gülmek', category:'verbs', level:'beginner' },
  { id:979, en:'lay', ru:'класть', tk:'goýmak', category:'verbs', level:'intermediate' },
  { id:980, en:'let', ru:'позволять', tk:'goýbermek', category:'verbs', level:'beginner' },
  { id:981, en:'likely', ru:'вероятно', tk:'mümkin', category:'basics', level:'intermediate' },
  { id:982, en:'long', ru:'долго', tk:'uzak', category:'basics', level:'beginner' },
  { id:983, en:'loud', ru:'громкий', tk:'güýçli', category:'adjectives', level:'beginner' },
  { id:984, en:'lovely', ru:'прекрасный', tk:'owadan', category:'adjectives', level:'beginner' },
  { id:985, en:'lucky', ru:'удачливый', tk:'bagtly', category:'adjectives', level:'beginner' },
  { id:986, en:'mention', ru:'упоминать', tk:'agzamak', category:'verbs', level:'intermediate' },
  { id:987, en:'miss', ru:'пропустить', tk:'ýitirim etmek', category:'verbs', level:'intermediate' },
  { id:988, en:'most', ru:'большинство', tk:'köpüsi', category:'basics', level:'intermediate' },
  { id:989, en:'much', ru:'много', tk:'köp', category:'basics', level:'beginner' },
  { id:990, en:'must', ru:'должен', tk:'gerek', category:'basics', level:'intermediate' },
  { id:991, en:'narrow', ru:'узкий', tk:'dar', category:'adjectives', level:'intermediate' },
  { id:992, en:'never', ru:'никогда', tk:'hiçwagt', category:'basics', level:'beginner' },
  { id:993, en:'next', ru:'следующий', tk:'indiki', category:'basics', level:'beginner' },
  { id:994, en:'nice', ru:'приятный', tk:'ýakymly', category:'adjectives', level:'beginner' },
  { id:995, en:'now', ru:'сейчас', tk:'häzir', category:'time', level:'beginner' },
  { id:996, en:'number', ru:'число', tk:'san', category:'numbers', level:'beginner' },
  { id:997, en:'only', ru:'только', tk:'diňe', category:'basics', level:'beginner' },
  { id:998, en:'other', ru:'другой', tk:'başga', category:'basics', level:'beginner' },
  { id:999, en:'outside', ru:'снаружи', tk:'daşynda', category:'basics', level:'beginner' },
  { id:1000, en:'own', ru:'владеть', tk:'eýe bolmak', category:'verbs', level:'intermediate' },
];

export const CATEGORIES = [
  { id:'all', tk:'Ähli sözler', ru:'Все слова', en:'All words', icon:'📚' },
  { id:'animals', tk:'Haýwanlar', ru:'Животные', en:'Animals', icon:'🐾' },
  { id:'food', tk:'Iýmit', ru:'Еда', en:'Food', icon:'🍎' },
  { id:'colors', tk:'Reňkler', ru:'Цвета', en:'Colors', icon:'🎨' },
  { id:'numbers', tk:'Sanlar', ru:'Числа', en:'Numbers', icon:'🔢' },
  { id:'family', tk:'Maşgala', ru:'Семья', en:'Family', icon:'👨‍👩‍👧' },
  { id:'body', tk:'Beden', ru:'Тело', en:'Body', icon:'🫀' },
  { id:'house', tk:'Öý', ru:'Дом', en:'House', icon:'🏠' },
  { id:'nature', tk:'Tebigat', ru:'Природа', en:'Nature', icon:'🌿' },
  { id:'transport', tk:'Ulag', ru:'Транспорт', en:'Transport', icon:'🚗' },
  { id:'school', tk:'Mekdep', ru:'Школа', en:'School', icon:'📖' },
  { id:'clothes', tk:'Egin-eşik', ru:'Одежда', en:'Clothes', icon:'👔' },
  { id:'professions', tk:'Kärler', ru:'Профессии', en:'Professions', icon:'💼' },
  { id:'verbs', tk:'Işlikler', ru:'Глаголы', en:'Verbs', icon:'⚡' },
  { id:'adjectives', tk:'Sypatlar', ru:'Прилагательные', en:'Adjectives', icon:'✨' },
  { id:'time', tk:'Wagt', ru:'Время', en:'Time', icon:'⏰' },
  { id:'health', tk:'Saglyk', ru:'Здоровье', en:'Health', icon:'🏥' },
  { id:'sports', tk:'Sport', ru:'Спорт', en:'Sports', icon:'⚽' },
  { id:'technology', tk:'Tehnologiýa', ru:'Технологии', en:'Technology', icon:'💻' },
  { id:'places', tk:'Ýerler', ru:'Места', en:'Places', icon:'📍' },
  { id:'basics', tk:'Esaslar', ru:'Основы', en:'Basics', icon:'🔤' },
  { id:'emotions', tk:'Duýgular', ru:'Эмоции', en:'Emotions', icon:'❤️' },
  { id:'science', tk:'Ylym', ru:'Наука', en:'Science', icon:'🔬' },
  { id:'music', tk:'Saz', ru:'Музыка', en:'Music', icon:'🎵' },
  { id:'money', tk:'Pul', ru:'Деньги', en:'Money', icon:'💰' },
  { id:'weather', tk:'Howa', ru:'Погода', en:'Weather', icon:'🌤️' },
  { id:'directions', tk:'Ugurlar', ru:'Направления', en:'Directions', icon:'🧭' },
  { id:'advanced', tk:'Çylşyrymly', ru:'Сложные', en:'Advanced', icon:'🎓' },
];
